#!/usr/bin/env python3
"""Thread spawn benchmarks (bench/spawn/design.md).

Generates one Goose program per (benchmark, parameter value), builds each
twice -- once timed, once with CHECK on, where every worker sends back a
checksum of what it received and main compares it -- runs them one at a
time, and writes results.md and results.json beside this file. Every
program times itself with os.clock_ns: a spawn is far below the noise of
process creation, so whole-process timing would measure nothing.

Baselines (baselines/spawn.c, .cpp, .rs) run the rows that have a C, C++ or
Rust counterpart, under the same calibration and batch protocol.

  python bench/spawn/spawn_bench.py                  # everything
  python bench/spawn/spawn_bench.py --only B,C4      # families or benchmark ids
  python bench/spawn/spawn_bench.py --quick          # 3 points per sweep, short batches
  python bench/spawn/spawn_bench.py --no-baselines   # Goose only
  python bench/spawn/spawn_bench.py --no-check       # skip the CHECK builds
  python bench/spawn/spawn_bench.py --report-only    # re-render from results.json
  python bench/spawn/spawn_bench.py --list           # print the plan and exit
"""

import argparse
import concurrent.futures
import hashlib
import json
import math
import os
import platform
import re
import statistics
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "scripts"))
import toolchain as tc

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
GEN = ROOT / "bench" / "gen" / "spawn"
BASEDIR = HERE / "baselines"
HW = os.cpu_count() or 4

KB, MB, GB = 1 << 10, 1 << 20, 1 << 30
SIZES = [8, 64, 512, 4 * KB, 32 * KB, 256 * KB, 1 * MB, 8 * MB]


# --- Goose program text ---------------------------------------------------------
#
# Every program has the same skeleton: `run(reps, sources...)` does the timed
# work and says how many units (spawns, tasks, round trips) that was;
# `check(sources...)` verifies what workers receive; main calibrates, warms up
# and prints one line per batch. Source data for arguments is built by main as
# locals and handed to run by reference: as globals they would grow
# gs_globals_t, which every worker callocs, and that is a cost of its own (B8).

SKELETON = """\
// Generated by bench/spawn/spawn_bench.py; do not edit.
// @ID@: @TITLE@ (@PARAM@ = @VALUE@)
import os;

let CHECK = @CHECK@;
let TARGET_NS = @TARGET@;
let BATCHES = @BATCHES@;
// No worker's checksum is this; comparing against it keeps what a worker
// reads observable without ever taking the branch.
let SENTINEL = -987654321;

struct Sum { v: i64 }
struct Out { units: i64, x: i64[4] }

fn bytes_of_len(n: i64) -> u8[>..] {
    var b: u8[>..] = [];
    for i in n { b.push((i % 251 + 1) as u8); }
    return b;
}

@DECLS@

fn run(reps: i64@SRCPARAMS_TAIL@) -> Out {
@RUN@
}

fn check(@SRCPARAMS@) {
@CHECKBODY@
}

fn teardown(@SRCPARAMS@) {
@TEARDOWN@
}

fn main() {
@SETUP@
    if CHECK {
        check(@SRCARGS@);
        teardown(@SRCARGS@);
        return;
    }
    // Every run's result reaches the output: a run with no side effects
    // (E6i) would otherwise be deleted from the calibration loop, which
    // would then double reps until it overflowed.
    var sink = 0;
    let w0 = clock_ns();
    var warm = 0;
    while warm < 50 && clock_ns() - w0 < TARGET_NS / 4 {
        sink += run(1@SRCARGS_TAIL@).x[0];
        warm++;
    }
    var reps = 1;
    loop {
        let t = clock_ns();
        sink += run(reps@SRCARGS_TAIL@).x[0];
        if clock_ns() - t >= TARGET_NS { break; }
        if reps >= 1099511627776 { abort("calibration never reached TARGET_NS"); }
        reps *= 2;
    }
    for b in BATCHES {
        let t = clock_ns();
        let o = run(reps@SRCARGS_TAIL@);
        let ns = clock_ns() - t;
        print("batch units=", o.units, " ns=", ns, " x0=", o.x[0], " x1=", o.x[1],
              " x2=", o.x[2], " x3=", o.x[3]);
    }
    print("sink ", sink);
    teardown(@SRCARGS@);
}
"""


def indent(text, n=4):
    pad = " " * n
    return "\n".join(pad + l if l.strip() else l for l in text.strip("\n").split("\n"))


@dataclass
class Prog:
    """The parts of one generated program that differ between benchmarks."""
    decls: str = ""
    run: str = ""
    check: str = '    print("check ok");'
    teardown: str = ""
    setup: str = ""
    # (name, type) of each main local handed to run/check/teardown by reference.
    sources: list = field(default_factory=list)
    defines: list = field(default_factory=list)

    def render(self, meta, check, target, batches):
        params = ", ".join(f"{n}: const {t}&" for n, t in self.sources)
        args = ", ".join(n for n, _ in self.sources)
        tail = lambda s: (", " + s) if s else ""
        subs = {
            "@ID@": meta["id"], "@TITLE@": meta["title"], "@PARAM@": meta["param"],
            "@VALUE@": str(meta["value"]),
            "@CHECK@": "true" if check else "false", "@TARGET@": str(target),
            "@BATCHES@": str(batches), "@DECLS@": self.decls.strip("\n"),
            "@SRCPARAMS_TAIL@": tail(params), "@SRCPARAMS@": params,
            "@SRCARGS_TAIL@": tail(args), "@SRCARGS@": args,
            "@RUN@": indent(self.run), "@CHECKBODY@": indent(self.check),
            "@TEARDOWN@": indent(self.teardown), "@SETUP@": indent(self.setup),
        }
        text = SKELETON
        for k, v in subs.items():
            text = text.replace(k, v)
        return text


# --- the serial spawn shape: one worker, its arguments and globals --------------
#
# An argument or a global is a kind plus a size. Each kind knows its parameter
# type, how main builds the source value, the expression that passes it, and
# the statements that fold it into the worker's checksum. The same statements
# run in `expect`, a plain function with the worker's parameters, so the
# CHECK build compares the worker's view against main's.

def arg_parts(i, kind, n=0, m=0):
    """(param type, setup, source (name, type) or None, spawn expr, fold)."""
    a, s = f"a{i}", f"src{i}"
    if kind == "i64":
        return "i64", "", None, f"i + {i + 1}", f"s += {a};"
    if kind == "fixed":
        t = f"i64[{n}]"
        setup = f"var {s}: {t} = [0; {n}];\n{s}[0] = {i + 3};\n{s}[{n - 1}] = {i + 5};"
        return t, setup, (s, t), s, f"s += {a}[0] + {a}[{n - 1}];"
    if kind == "resz":
        t = "i64[>..]"
        setup = f"var {s}: {t} = [];\nfor j in {n} {{ {s}.push(j + {i}); }}"
        return t, setup, (s, t), f"copy({s})", \
            f"s += {a}.len;\nif {a}.len > 0 {{ s += {a}[{a}.len - 1]; }}"
    if kind == "var":
        t = "u8[]"
        setup = f"let {s}: {t} = bytes_of_len({n});"
        return t, setup, (s, t), f"copy({s})", \
            f"s += {a}.len;\nif {a}.len > 0 {{ s += {a}[{a}.len - 1]; }}"
    if kind == "strings":
        # n strings of m bytes each.
        t = "u8[][>..]"
        setup = f"var {s}: {t} = [];\nfor j in {n} {{ {s}.push(bytes_of_len({m})); }}"
        return t, setup, (s, t), f"copy({s})", f"s += {a}.len;"
    if kind == "frame":
        t = "Bag"
        setup = (f"var {s} = Bag {{ id: {i + 7}, data: [] }};\n"
                 f"for j in {n} {{ {s}.data.push(j); }}")
        return t, setup, (s, t), f"copy({s})", f"s += {a}.id + {a}.data.len;"
    raise ValueError(kind)


def global_parts(i, kind, n=0, prefix="g"):
    """(declaration, setup, fold)."""
    g = f"{prefix}{i}"
    if kind == "i64":
        return f"var {g}: i64 = {i + 1};", "", f"s += {g};"
    if kind == "fixed":
        return (f"var {g}: i64[{n}] = [0; {n}];", f"{g}[0] = {i + 3};\n{g}[{n - 1}] = {i + 5};",
                f"s += {g}[0] + {g}[{n - 1}];")
    if kind == "resz":
        return (f"var {g}: i64[>..] = [];", f"for j in {n} {{ {g}.push(j + {i}); }}",
                f"s += {g}.len;\nif {g}.len > 0 {{ s += {g}[{g}.len - 1]; }}")
    if kind == "var":
        return (f"var {g}: u8[] = bytes_of_len({n});", "",
                f"s += {g}.len;\nif {g}.len > 0 {{ s += {g}[{g}.len - 1]; }}")
    if kind == "pool":
        # 2n slots, every other one freed: n freelist entries none of which
        # touch, so the freelist holds n spans.
        return (f"reusable var {g}: i64[>..] = [];",
                f"for j in {2 * n + 1} {{ {g}.alloc_index(j); }}\n"
                f"for j in {n} {{ {g}.free(2 * j); }}",
                f"s += {g}.len;")
    if kind == "const":
        return (f"const {g}: i64[4] = [{i}, 1, 2, {i + 3}];", "", f"s += {g}[0] + {g}[3];")
    raise ValueError(kind)


def serial(args=(), used=(), unused=(), cold=(), body="", body_decls=""):
    """A worker given `args`, naming the globals in `used`, the program also
    declaring the never-named `unused` ones and the `cold` ones named only on
    a branch the worker never takes; spawned and waited for one at a time.
    Each of args/used/unused/cold is a list of (kind, n[, m]) tuples."""
    p = Prog()
    params, setup, spawn, fold, decls = [], [], [], [], [body_decls]
    if any(a[0] == "frame" for a in args):
        decls.append("struct Bag { id: i64, data: i64[>..] }")
    for i, a in enumerate(args):
        t, st, src, ex, fo = arg_parts(i, *a)
        params.append(f"a{i}: {t}")
        if st:
            setup.append(st)
        if src:
            p.sources.append(src)
        spawn.append(ex)
        fold.append(fo)
    # Prefixes that no index can turn into a type name (u8, i64...).
    for prefix, group in (("g", used), ("unused", unused), ("cold", cold)):
        for i, g in enumerate(group):
            d, st, fo = global_parts(i, *g, prefix=prefix)
            decls.append(d)
            if st:
                setup.append(st)
            if prefix == "g":
                fold.append(fo)
            elif prefix == "cold":
                fold.append(f"if s == SENTINEL {{\n{indent(fo)}\n}}")
    if body:
        fold.append(body)
    fold_text = "var s = 0;\n" + "\n".join(fold)
    plist = ", ".join(params)
    decls.append(f"thread_fn w({plist}) {{\n{indent(fold_text)}\n"
                 f"    if CHECK || s == SENTINEL {{ qput(Sum {{ v: s }}); }}\n}}")
    decls.append(f"fn expect({plist}) -> i64 {{\n{indent(fold_text)}\n    return s;\n}}")
    p.decls = "\n\n".join(d for d in decls if d)
    sargs = ", ".join(["w"] + spawn)
    eargs = ", ".join(spawn)
    p.setup = "\n".join(setup)
    p.run = (f"for i in reps {{ thread_wait(thread_spawn({sargs})); }}\n"
             "return Out { units: reps, x: [0; 4] };")
    p.check = f"""\
for i in 3 {{
    thread_wait(thread_spawn({sargs}));
    let got = qget<Sum>().v;
    let want = expect({eargs});
    if got != want {{
        print("check failed: got ", got, " want ", want);
        exit(1);
    }}
}}
print("check ok");"""
    return p


# --- worker bodies for D ----------------------------------------------------------

def stack_chain(k):
    """k nested functions, each holding a resizable local live across the call
    to the next: the worker's call depth reaches k data stacks."""
    fns = ["fn chain0() -> i64 { return 0; }"]
    for j in range(1, k + 1):
        fns.append(f"fn chain{j}() -> i64 {{\n    var a: i64[>..] = [];\n    a.push({j});\n"
                   f"    let r = chain{j - 1}();\n    return a.len + a[0] + r;\n}}")
    return "\n\n".join(fns), f"s += chain{k}();"


def native_recursion(nbytes):
    """Recursion touching about nbytes of native stack (a 480-byte local array
    per frame, below the 4096-byte line past which locals go to data stacks)."""
    depth = max(0, nbytes // 512)
    decl = """\
recursive fn deep(d: i64) -> i64 {
    var a: i64[60] = [0; 60];
    a[d % 60] = d;
    if d == 0 { return a[0]; }
    return deep(d - 1) + a[(d * 7) % 60];
}"""
    return decl, f"s += deep({depth});"


# --- custom shapes -------------------------------------------------------------------

def prog_phases():
    p = Prog()
    p.decls = """\
struct Stamp { a: i64, b: i64 }
thread_fn w() {
    let a = clock_ns();
    qput(Stamp { a: a, b: clock_ns() });
}"""
    # x0: thread_spawn returns; x1: spawn call to the worker's first
    # instruction; x2: worker's last instruction (its qput) to thread_wait
    # returning; x3: the worker body between them.
    p.run = """\
var x: i64[4] = [0; 4];
for i in reps {
    let t0 = clock_ns();
    let id = thread_spawn(w);
    let t1 = clock_ns();
    thread_wait(id);
    let t2 = clock_ns();
    let st = qget<Stamp>();
    x[0] += t1 - t0;
    x[1] += st.a - t0;
    x[2] += t2 - st.b;
    x[3] += st.b - st.a;
}
return Out { units: reps, x: x };"""
    p.check = """\
thread_wait(thread_spawn(w));
let st = qget<Stamp>();
if st.b < st.a { print("check failed: stamps out of order"); exit(1); }
print("check ok");"""
    return p


EMPTY_WORKER = """\
thread_fn w(i: i64) {
    if CHECK { qput(Sum { v: i }); }
}"""


def check_counts(n_expr, sum_expr):
    """Spawns n workers of EMPTY_WORKER's shape and checks every one ran."""
    return f"""\
var total = 0;
for k in {n_expr} {{ total += qget<Sum>().v; }}
if total != {sum_expr} {{ print("check failed: ", total); exit(1); }}
print("check ok");"""


def prog_burst(n, order="fwd"):
    p = Prog()
    p.decls = EMPTY_WORKER
    wait = ("for id in ids { thread_wait(id); }" if order == "fwd" else
            "var k = ids.len - 1;\nwhile k >= 0 { thread_wait(ids[k]); k -= 1; }")
    # x0: time spent in the spawn calls alone.
    p.run = f"""\
var x: i64[4] = [0; 4];
var ids: i64[>..] = [];
for r in reps {{
    ids.clear();
    let t0 = clock_ns();
    for i in {n} {{ ids.push(thread_spawn(w, i)); }}
    x[0] += clock_ns() - t0;
{indent(wait)}
}}
return Out {{ units: reps * {n}, x: x }};"""
    p.check = f"""\
var ids: i64[>..] = [];
for i in {n} {{ ids.push(thread_spawn(w, i)); }}
for id in ids {{ thread_wait(id); }}
""" + check_counts(n, n * (n - 1) // 2)
    return p


def prog_live(n_idle):
    p = Prog()
    p.decls = EMPTY_WORKER + """

struct Quit { v: i64 }
thread_fn idle() {
    let q = qget<Quit>();
}"""
    # The idle population is started before timing, by main, and released at
    # the end; it must not be in run, which the calibration calls repeatedly.
    p.setup = f"var idle_ids: i64[>..] = [];\nfor k in {n_idle} {{ idle_ids.push(thread_spawn(idle)); }}"
    p.sources = [("idle_ids", "i64[>..]")]
    p.run = """\
for i in reps { thread_wait(thread_spawn(w, i)); }
return Out { units: reps, x: [0; 4] };"""
    p.check = """\
for i in 4 { thread_wait(thread_spawn(w, i)); }
""" + check_counts(4, 6)
    p.teardown = """\
for id in idle_ids { qput(Quit { v: 0 }); }
for id in idle_ids { thread_wait(id); }"""
    return p


def prog_parallel(n_spawners):
    p = Prog()
    p.decls = EMPTY_WORKER + """

thread_fn spawner(m: i64) {
    for i in m { thread_wait(thread_spawn(w, 1)); }
}"""
    p.run = f"""\
var ids: i64[>..] = [];
for k in {n_spawners} {{ ids.push(thread_spawn(spawner, reps)); }}
for id in ids {{ thread_wait(id); }}
return Out {{ units: reps * {n_spawners}, x: [0; 4] }};"""
    p.check = f"""\
var ids: i64[>..] = [];
for k in {n_spawners} {{ ids.push(thread_spawn(spawner, 3)); }}
for id in ids {{ thread_wait(id); }}
""" + check_counts(3 * n_spawners, 3 * n_spawners)
    return p


def prog_tree(depth):
    p = Prog()
    p.decls = """\
thread_fn node(d: i64) {
    if CHECK { qput(Sum { v: 1 }); }
    if d > 0 {
        let a = thread_spawn(node, d - 1);
        let b = thread_spawn(node, d - 1);
        thread_wait(a);
        thread_wait(b);
    }
}"""
    nodes = (2 << depth) - 1
    p.run = f"""\
for r in reps {{ thread_wait(thread_spawn(node, {depth})); }}
return Out {{ units: reps * {nodes}, x: [0; 4] }};"""
    p.check = f"thread_wait(thread_spawn(node, {depth}));\n" + check_counts(nodes, nodes)
    return p


def prog_chain(depth):
    p = Prog()
    # Each link copies a 1 KB global from the link that spawned it, which has
    # already changed it: what a worker's worker sees is its parent's.
    p.decls = """\
var g: i64[128] = [0; 128];
thread_fn link(d: i64) {
    g[0] += 1;
    if CHECK { qput(Sum { v: g[0] }); }
    if d > 0 { thread_wait(thread_spawn(link, d - 1)); }
}"""
    p.run = f"""\
for r in reps {{ thread_wait(thread_spawn(link, {depth - 1})); }}
return Out {{ units: reps * {depth}, x: [0; 4] }};"""
    p.check = (f"thread_wait(thread_spawn(link, {depth - 1}));\n"
               + check_counts(depth, depth * (depth + 1) // 2))
    return p


WORK = """\
struct Res { v: i64 }
struct Job { k: i64, seed: i64 }

// k rounds of xorshift: the same task the C, C++ and Rust rows run.
fn work(k: i64, seed: i64) -> i64 {
    var r: u64 = seed as! u64 * 2654435761 + 1;
    for i in k {
        r ^= r << 13;
        r ^= r >> 7;
        r ^= r << 17;
    }
    return (r & 65535) as! i64;
}"""


def prog_task(mode, k):
    p = Prog()
    if mode == "spawn":
        p.decls = WORK + """

thread_fn task(k: i64, seed: i64) { qput(Res { v: work(k, seed) }); }"""
        # Waves of at most 256 live tasks, as the baselines run.
        p.run = f"""\
var ids: i64[>..] = [];
var done = 0;
var acc = 0;
while done < reps {{
    let n = if reps - done < 256 {{ reps - done }} else {{ 256 }};
    ids.clear();
    for j in n {{ ids.push(thread_spawn(task, {k}, done + j)); }}
    for id in ids {{ thread_wait(id); }}
    for j in n {{ acc += qget<Res>().v; }}
    done += n;
}}
return Out {{ units: reps, x: [acc, 0, 0, 0] }};"""
        p.check = f"""\
thread_wait(thread_spawn(task, {k}, 5));
if qget<Res>().v != work({k}, 5) {{ print("check failed"); exit(1); }}
print("check ok");"""
    elif mode == "pool":
        p.decls = WORK + """

thread_fn pooled() {
    loop {
        let j = qget<Job>();
        guard j.k >= 0 else { break; }
        qput(Res { v: work(j.k, j.seed) });
    }
}"""
        p.setup = f"var pool_ids: i64[>..] = [];\nfor k in {HW} {{ pool_ids.push(thread_spawn(pooled)); }}"
        p.sources = [("pool_ids", "i64[>..]")]
        p.run = f"""\
for i in reps {{ qput(Job {{ k: {k}, seed: i }}); }}
var acc = 0;
for i in reps {{ acc += qget<Res>().v; }}
return Out {{ units: reps, x: [acc, 0, 0, 0] }};"""
        p.check = f"""\
qput(Job {{ k: {k}, seed: 5 }});
if qget<Res>().v != work({k}, 5) {{ print("check failed"); exit(1); }}
print("check ok");"""
        p.teardown = """\
for id in pool_ids { qput(Job { k: -1, seed: 0 }); }
for id in pool_ids { thread_wait(id); }"""
    else:
        p.decls = WORK
        p.run = f"""\
var acc = 0;
for i in reps {{ acc += work({k}, i); }}
return Out {{ units: reps, x: [acc, 0, 0, 0] }};"""
    return p


def prog_queue():
    p = Prog()
    p.decls = """\
struct Ping { v: i64 }
struct Pong { v: i64 }
thread_fn echo() {
    loop {
        let p = qget<Ping>();
        guard p.v >= 0 else { break; }
        qput(Pong { v: p.v });
    }
}"""
    p.setup = "var echo_ids: i64[>..] = [];\necho_ids.push(thread_spawn(echo));"
    p.sources = [("echo_ids", "i64[>..]")]
    p.run = """\
for i in reps {
    qput(Ping { v: i });
    let r = qget<Pong>();
}
return Out { units: reps, x: [0; 4] };"""
    p.check = """\
qput(Ping { v: 42 });
if qget<Pong>().v != 42 { print("check failed"); exit(1); }
print("check ok");"""
    p.teardown = """\
qput(Ping { v: -1 });
for id in echo_ids { thread_wait(id); }"""
    return p


# --- the plan ---------------------------------------------------------------------------
#
# A benchmark is a sweep: `points` maps each parameter value to a Prog maker
# and, where one exists, a baseline (mode, a, b). `fit` names the unit of the
# fitted slope, when the sweep is meant to be linear in its parameter; `x`
# gives the fitted quantity for a value when it is not the value itself.

@dataclass
class Bench:
    id: str
    family: str
    title: str
    param: str
    values: list
    make: object                       # value -> Prog, or None for baseline-only
    baseline: object = None            # value -> (mode, a, b) or None
    fit: str = ""                      # unit of the slope, e.g. "ns per global"
    fitx: object = None                # value -> x for the fit
    fmt: object = str                  # value -> table label
    baseline_note: str = ""
    langs: tuple = ("c", "cpp", "rs")


def size_label(n):
    for unit, k in (("GB", GB), ("MB", MB), ("KB", KB)):
        if n >= k and n % k == 0:
            return f"{n // k} {unit}"
    return f"{n} B"


def per_kb(n):
    return n / KB


def nelems(nbytes):
    return max(1, nbytes // 8)


def plan():
    B = []
    add = B.append
    payload = "malloc + memcpy / captured vector / cloned Vec of the same bytes"

    # A. Floor and phases.
    add(Bench("A1", "A", "empty worker, serial spawn + wait", "—", [0],
              lambda v: serial(), baseline=lambda v: ("empty", 0, 0)))
    add(Bench("A2", "A", "phases of A1 (worker reports stamps through a queue)", "—", [0],
              lambda v: prog_phases()))
    add(Bench("A3", "A", "burst: spawn N, then wait all", "N", [1, 4, 16, 64, 256, 1024],
              lambda v: prog_burst(v), baseline=lambda v: ("burst", v, 0)))

    # B. Globals.
    add(Bench("B1", "B", "K used i64 globals", "K", [0, 1, 4, 16, 64, 256, 1024],
              lambda v: serial(used=[("i64",)] * v), fit="ns per global"))
    add(Bench("B2", "B", "one used fixed global i64[n]", "bytes", SIZES,
              lambda v: serial(used=[("fixed", nelems(v))]), baseline=lambda v: ("bytes", v, 0),
              fit="ns per KB", fitx=per_kb, fmt=size_label, baseline_note=payload))
    add(Bench("B3", "B", "K used resizable globals, 1 element each", "K", [0, 1, 2, 4, 8, 16, 64],
              lambda v: serial(used=[("resz", 1)] * v), fit="ns per region"))
    add(Bench("B4", "B", "one used resizable global i64[>..]", "bytes", [0] + SIZES + [64 * MB],
              lambda v: serial(used=[("resz", v // 8)]), baseline=lambda v: ("bytes", v, 0),
              fit="ns per KB", fitx=per_kb, fmt=size_label, baseline_note=payload))
    add(Bench("B5", "B", "one used variable-size global u8[]", "bytes", SIZES,
              lambda v: serial(used=[("var", v)]), baseline=lambda v: ("bytes", v, 0),
              fit="ns per KB", fitx=per_kb, fmt=size_label, baseline_note=payload))
    add(Bench("B6", "B", "one used reusable pool global, F freelist spans", "F", [0, 64, 4096],
              lambda v: serial(used=[("pool", v)]), fit="ns per span"))
    add(Bench("B7", "B", "K i64 globals the worker never names", "K", [0, 64, 1024, 16384],
              lambda v: serial(unused=[("i64",)] * v), fit="ns per global"))
    add(Bench("B8", "B", "one fixed global i64[n] the worker never names", "bytes", SIZES,
              lambda v: serial(unused=[("fixed", nelems(v))]), fit="ns per KB", fitx=per_kb,
              fmt=size_label))
    add(Bench("B9", "B", "K 1 MB resizable globals the worker never names", "K", [0, 1, 16],
              lambda v: serial(unused=[("resz", MB // 8)] * v), fit="ns per global"))
    add(Bench("B10", "B", "K used const globals (static data, control)", "K", [0, 16, 1024],
              lambda v: serial(used=[("const",)] * v), fit="ns per global"))
    add(Bench("B11", "B", "1 MB fixed global named only on a branch never taken", "cold", [0, 1],
              lambda v: serial(cold=[("fixed", MB // 8)] * v),
              fmt=lambda v: "named" if v else "absent"))

    # C. Arguments.
    add(Bench("C1", "C", "K i64 arguments", "K", [0, 1, 2, 4, 8, 16, 32, 64],
              lambda v: serial(args=[("i64",)] * v), baseline=lambda v: ("args", v, 0),
              fit="ns per argument",
              baseline_note="C: malloc + memcpy of K i64; C++/Rust: a [i64; K] captured by value"))
    c2 = sorted(set(SIZES + [4096, 4104]))
    add(Bench("C2", "C", "one fixed argument i64[n] (by pointer above 4096 B)", "bytes", c2,
              lambda v: serial(args=[("fixed", nelems(v))]), baseline=lambda v: ("bytes", v, 0),
              fit="ns per KB", fitx=per_kb, fmt=size_label, baseline_note=payload))
    add(Bench("C3", "C", "K resizable arguments, 1 element each", "K", [0, 1, 2, 4, 8, 16],
              lambda v: serial(args=[("resz", 1)] * v), fit="ns per region"))
    add(Bench("C4", "C", "one resizable argument i64[>..]", "bytes", [0] + SIZES + [64 * MB],
              lambda v: serial(args=[("resz", v // 8)]), baseline=lambda v: ("bytes", v, 0),
              fit="ns per KB", fitx=per_kb, fmt=size_label, baseline_note=payload))
    add(Bench("C5", "C", "one variable-size argument u8[]", "bytes", SIZES,
              lambda v: serial(args=[("var", v)]), baseline=lambda v: ("bytes", v, 0),
              fit="ns per KB", fitx=per_kb, fmt=size_label, baseline_note=payload))
    # 1 MB of string bytes in W strings; a C counterpart would be C4.
    c6 = [1, 64, 1024, 16384, 65536]
    add(Bench("C6", "C", "one u8[][>..] of W strings totalling 1 MB", "W", c6,
              lambda v: serial(args=[("strings", v, MB // v)]),
              baseline=lambda v: ("strings", v, MB // v), fit="ns per string",
              baseline_note="C++ vector<string> / Rust Vec<String> captured by value",
              langs=("cpp", "rs")))
    add(Bench("C7", "C", "one struct { id, data: i64[>..] } (frame object)", "bytes",
              [0, 64, 4 * KB, 256 * KB, 8 * MB],
              lambda v: serial(args=[("frame", v // 8)]), baseline=lambda v: ("bytes", v, 0),
              fit="ns per KB", fitx=per_kb, fmt=size_label, baseline_note=payload))

    # D. The worker's own storage.
    def d1(k):
        decl, body = stack_chain(k)
        return serial(body=body, body_decls=decl)

    def d2(n):
        return serial(body=f"var t: i64[>..] = [];\nfor j in {n // 8} {{ t.push(j); }}\ns += t.len;")

    def d3(n):
        decl, body = native_recursion(n)
        return serial(body=body, body_decls=decl)

    add(Bench("D1", "D", "data stacks the worker's call depth reserves", "stacks",
              [0, 1, 4, 16, 64], d1, fit="ns per region"))
    add(Bench("D2", "D", "bytes the worker pushes to a resizable local", "bytes",
              [0, 64 * KB, 1 * MB, 16 * MB], d2, fit="ns per KB", fitx=per_kb, fmt=size_label))
    add(Bench("D3", "D", "native stack the worker touches", "bytes", [0, 64 * KB, 256 * KB],
              d3, fit="ns per KB", fitx=per_kb, fmt=size_label))

    # E. Topology and contention.
    add(Bench("E1f", "E", "burst of N, waited oldest first", "N", [16, 256, 1024],
              lambda v: prog_burst(v, "fwd"), fit="ns per spawn per live worker"))
    add(Bench("E1r", "E", "burst of N, waited newest first", "N", [16, 256, 1024],
              lambda v: prog_burst(v, "rev"), fit="ns per spawn per live worker"))
    add(Bench("E2", "E", "serial spawn + wait beside L idle workers", "L", [0, 16, 256, 1024],
              prog_live, baseline=lambda v: ("live", 0, v), fit="ns per idle worker"))
    ps = sorted(set([1, 2, 4, 8, HW]))
    add(Bench("E3", "E", "P threads each spawning + waiting serially", "P", ps,
              prog_parallel, baseline=lambda v: ("parallel", v, 0)))
    add(Bench("E4", "E", "binary fork-join tree of depth d (ns per node)", "d", [4, 6, 8, 10],
              prog_tree, baseline=lambda v: ("tree", v, 0)))
    add(Bench("E5", "E", "chain: each worker spawns the next, 1 KB global each", "depth",
              [1, 16, 256], prog_chain))
    ks = [0, 100, 1000, 10000, 100000]
    for mode, mid in (("spawn", "E6s"), ("pool", "E6p"), ("inline", "E6i")):
        what = {"spawn": "a worker spawned per task, waves of 256",
                "pool": f"a pool of {HW} workers fed by qput/qget",
                "inline": "on main's thread, no workers (the work alone)"}[mode]
        bl = {"spawn": lambda v: ("task_spawn", v, 0), "pool": lambda v: ("task_pool", v, HW),
              "inline": lambda v: ("task_inline", v, 0)}[mode]
        add(Bench(mid, "E", f"task of k xorshift rounds: {what}", "k", ks,
                  (lambda m: lambda v: prog_task(m, v))(mode), baseline=bl))

    # F. Build configuration.
    for rid, title, shape in (("F1a", "A1 under GS_STACK_RESERVE", lambda: serial()),
                              ("F1b", "B3 at K = 8 under GS_STACK_RESERVE",
                               lambda: serial(used=[("resz", 1)] * 8))):
        def mk(v, shape=shape):
            p = shape()
            p.defines = [f"GS_STACK_RESERVE={v}ull"]
            return p
        add(Bench(rid, "F", title, "reserve", [16 * MB, 256 * MB, 2 * GB, 64 * GB], mk,
                  fmt=size_label))

    # G. Reference costs.
    add(Bench("G1", "G", "qput + qget round trip of an i64 to a worker and back", "—", [0],
              lambda v: prog_queue()))
    add(Bench("G2", "G", "one region: mmap + mprotect guard + munmap (C)", "reserve",
              [16 * MB, 256 * MB, 2 * GB], None, baseline=lambda v: ("region", v, 0),
              fmt=size_label, langs=("c",)))
    return B


def quick_values(vals):
    if len(vals) <= 3:
        return vals
    return [vals[0], vals[len(vals) // 2], vals[-1]]


# --- building -----------------------------------------------------------------------------

def sha(*parts):
    h = hashlib.sha256()
    for p in parts:
        h.update(p if isinstance(p, bytes) else str(p).encode())
        h.update(b"\0")
    return h.hexdigest()[:12]


class Builder:
    def __init__(self, goose, cc, log):
        self.goose = Path(goose)
        st = self.goose.stat()
        self.goose_id = f"{st.st_size}-{st.st_mtime_ns}"
        self.cc = cc
        self.log = log

    def goose_program(self, name, text, defines):
        key = sha(text, self.goose_id, self.cc.name, self.cc.cc, *defines)
        exe = GEN / f"{name}-{key}{tc.EXE_SUFFIX}"
        if exe.exists():
            return exe, None
        src = GEN / f"{name}.goose"
        tc.write_text(src, text)
        cfile = GEN / f"{name}.c"
        code, out, err = tc.run_capture([self.goose, "-O2", "--standalone", "-o", cfile, src])
        tc.write_text(GEN / f"{name}.goose.log", out + err)
        if code != 0:
            return None, f"goose failed, see {name}.goose.log"
        ok, _ = self.cc.compile(cfile, exe, opt=2, defines=defines, log=GEN / f"{name}.cc.log")
        return (exe, None) if ok else (None, f"{self.cc.name} failed, see {name}.cc.log")

    def baselines(self, langs):
        out = {}
        if "c" in langs:
            exe = GEN / f"base_c{tc.EXE_SUFFIX}"
            ok, msg = self.cc.compile(BASEDIR / "spawn.c", exe, opt=2, log=GEN / "base_c.log")
            out["c"] = exe if ok else None
        if "cpp" in langs:
            exe = GEN / f"base_cpp{tc.EXE_SUFFIX}"
            ok, msg = self.cc.compile(BASEDIR / "spawn.cpp", exe, opt=2, cpp=True,
                                      log=GEN / "base_cpp.log")
            out["cpp"] = exe if ok else None
        if "rs" in langs:
            rustc = tc.find_rustc()
            exe = GEN / f"base_rs{tc.EXE_SUFFIX}"
            if rustc:
                code, o, e = tc.run_capture([rustc, "-O", "-C", "codegen-units=1", "-o", exe,
                                             BASEDIR / "spawn.rs"])
                tc.write_text(GEN / "base_rs.log", o + e)
                out["rs"] = exe if code == 0 else None
            else:
                out["rs"] = None
        return out


# --- running ---------------------------------------------------------------------------------

BATCH_RE = re.compile(r"^batch (.*)$")


def parse_batches(out):
    rows = []
    for line in out.splitlines():
        m = BATCH_RE.match(line.strip())
        if not m:
            continue
        kv = dict(f.split("=", 1) for f in m.group(1).split())
        rows.append({k: int(v) for k, v in kv.items()})
    return rows


def quantile(xs, q):
    xs = sorted(xs)
    if not xs:
        return float("nan")
    k = (len(xs) - 1) * q
    lo, hi = math.floor(k), math.ceil(k)
    return xs[lo] + (xs[hi] - xs[lo]) * (k - lo)


def summarize(rows):
    per = [r["ns"] / r["units"] for r in rows if r.get("units")]
    s = {"median": statistics.median(per), "p10": quantile(per, 0.1),
         "p90": quantile(per, 0.9), "min": min(per), "batches": len(per),
         "units": rows[0]["units"]}
    for k in ("x0", "x1", "x2", "x3"):
        if any(r.get(k) for r in rows):
            s[k] = statistics.median(r[k] / r["units"] for r in rows)
    return s


def run_point(exe, args, label, reps_noisy=1):
    """Runs one timed program, re-running once if its spread is wide."""
    for attempt in range(1 + reps_noisy):
        r = tc.run_measured(exe, args)
        if r.code != 0:
            return {"error": f"exit {r.code}: {(r.err or r.out)[-300:]}"}
        rows = parse_batches(r.out)
        if not rows:
            return {"error": f"no batch lines: {r.out[-300:]}"}
        s = summarize(rows)
        s["peak"] = r.peak
        if s["p90"] <= 1.5 * s["p10"] or attempt == reps_noisy:
            if s["p90"] > 1.5 * s["p10"]:
                s["noisy"] = True
            return s
        print(f"    {label}: spread {s['p90'] / s['p10']:.2f}x, re-measuring", flush=True)


def fit_line(xs, ys):
    n = len(xs)
    if n < 2:
        return None
    mx, my = sum(xs) / n, sum(ys) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    if sxx == 0:
        return None
    b = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / sxx
    a = my - b * mx
    ss_tot = sum((y - my) ** 2 for y in ys)
    ss_res = sum((y - (a + b * x)) ** 2 for x, y in zip(xs, ys))
    r2 = 1 - ss_res / ss_tot if ss_tot else 1.0
    return {"a": a, "b": b, "r2": r2}


# --- report ---------------------------------------------------------------------------------------

LANG_NAMES = {"c": "C pthread", "cpp": "C++ std::thread", "rs": "Rust std::thread"}

FAMILY_TITLES = {
    "A": "A. Floor and phases",
    "B": "B. Globals",
    "C": "C. Arguments",
    "D": "D. The worker's own storage",
    "E": "E. Topology and contention",
    "F": "F. Build configuration",
    "G": "G. Reference costs",
}

PHASE_NAMES = {
    "A2": ["spawn call", "start latency", "exit to wait return", "body (two clock reads)"],
    "A3": ["spawn calls alone"], "E1f": ["spawn calls alone"], "E1r": ["spawn calls alone"],
}


def fmt_ns(v):
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "—"
    if v >= 1e6:
        return f"{v / 1e6:,.2f} ms"
    if v >= 1e4:
        return f"{v / 1e3:,.1f} µs"
    if v >= 1e3:
        return f"{v / 1e3:,.2f} µs"
    return f"{v:,.0f} ns"


def fmt_cell(s):
    if not s:
        return "—"
    if "error" in s:
        return "error"
    cell = fmt_ns(s["median"])
    if s.get("noisy"):
        cell += " ~"
    return cell


def render(results, benches, path):
    meta = results["meta"]
    L = []
    w = L.append
    w("# Thread spawn benchmarks: results\n")
    w("Generated by `bench/spawn/spawn_bench.py`; the design, the cost model and "
      "the predictions are in [design.md](design.md). Times are per unit (a "
      "spawn + wait unless the row says otherwise), the median over batches "
      "measured in-process; `~` marks a point whose p90/p10 spread stayed above "
      "1.5x after one re-run.\n")
    w(f"Machine: {meta['cpu']}, {meta['cores']} hardware threads, {meta['os']}. "
      f"C toolchain: {meta['cc']}. Measured {meta['date']}"
      f"{' (quick mode)' if meta.get('quick') else ''}.\n")

    # The cost model, filled in.
    w("## Fitted cost model\n")
    w("Least-squares slopes over each sweep's medians. A low R² means the cost "
      "is not linear in that parameter; read the table for its shape instead.\n")
    w("| benchmark | slope | intercept | R² |")
    w("|---|---|---|---|")
    for b in benches:
        f = results["fits"].get(b.id)
        if f:
            w(f"| {b.id} {b.title} | {f['b']:,.2f} {b.fit} | {fmt_ns(f['a'])} | {f['r2']:.3f} |")
    w("")

    by_family = {}
    for b in benches:
        by_family.setdefault(b.family, []).append(b)
    for fam, bs in by_family.items():
        w(f"## {FAMILY_TITLES[fam]}\n")
        for b in bs:
            pts = results["points"].get(b.id, {})
            if not pts:
                continue
            w(f"### {b.id}: {b.title}\n")
            if b.baseline_note:
                w(f"Baselines: {b.baseline_note}.\n")
            langs = [l for l in b.langs if b.baseline and any(
                pts.get(str(v), {}).get(l) for v in b.values)]
            phases = PHASE_NAMES.get(b.id, [])
            head = [b.param]
            if b.make:
                head += ["Goose", "p10-p90"] + phases
            head += [LANG_NAMES[l] for l in langs]
            if b.make:
                head += ["Goose peak", "check"]
            w("| " + " | ".join(head) + " |")
            w("|" + "---|" * len(head))
            for v in b.values:
                p = pts.get(str(v))
                if not p:
                    continue
                g = p.get("goose")
                row = [b.fmt(v)]
                if b.make:
                    if g and "error" not in g:
                        row += [fmt_cell(g), f"{fmt_ns(g['p10'])}-{fmt_ns(g['p90'])}"]
                        row += [fmt_ns(g.get(f"x{i}")) for i in range(len(phases))]
                    else:
                        err = (g or {}).get("error", "not run")
                        row += [f"error: {err[:60]}", ""] + [""] * len(phases)
                for l in langs:
                    row.append(fmt_cell(p.get(l)))
                if b.make:
                    row.append(f"{g['peak'] / MB:,.1f} MB" if g and "peak" in g else "—")
                    row.append(p.get("check", "—"))
                w("| " + " | ".join(row) + " |")
            f = results["fits"].get(b.id)
            if f:
                w(f"\nFit: {fmt_ns(f['a'])} + {f['b']:,.2f} {b.fit} (R² {f['r2']:.3f}).")
            w("")
    tc.write_text(path, "\n".join(L) + "\n")


# --- main ---------------------------------------------------------------------------------------

def select(benches, only):
    if not only:
        return benches
    keys = [k.strip() for k in only.split(",") if k.strip()]
    return [b for b in benches if any(b.id == k or b.family == k or
                                      (len(k) > 1 and b.id.startswith(k)) for k in keys)]


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--exe", help="the goose compiler (default: found as the tests find it)")
    ap.add_argument("--cc", help="C toolchain name (default: clang if present)")
    ap.add_argument("--only", help="comma-separated families (A..G) or benchmark ids")
    ap.add_argument("--quick", action="store_true", help="3 points per sweep, short batches")
    ap.add_argument("--target-ms", type=float, help="minimum batch length (default 100, quick 20)")
    ap.add_argument("--batches", type=int, help="batches per point (default 15, quick 5)")
    ap.add_argument("--no-baselines", action="store_true")
    ap.add_argument("--no-check", action="store_true")
    ap.add_argument("--force", action="store_true", help="run even if the machine is busy")
    ap.add_argument("--jobs", type=int, default=HW, help="parallel builds")
    ap.add_argument("--report-only", action="store_true")
    ap.add_argument("--list", action="store_true", help="print the plan and exit")
    args = ap.parse_args()
    tc.setup_console()

    benches = select(plan(), args.only)
    if args.quick:
        for b in benches:
            b.values = quick_values(b.values)
    if args.list:
        n = 0
        for b in benches:
            n += len(b.values)
            print(f"{b.id:5} {b.title}  [{b.param}: {', '.join(b.fmt(v) for v in b.values)}]")
        print(f"{len(benches)} benchmarks, {n} points")
        return 0

    rpath = HERE / "results.json"
    if args.report_only:
        results = json.loads(rpath.read_text())
        render(results, plan(), HERE / "results.md")
        print(f"wrote {HERE / 'results.md'}")
        return 0

    target = int((args.target_ms or (20 if args.quick else 100)) * 1e6)
    batches = args.batches or (5 if args.quick else 15)

    if hasattr(os, "getloadavg") and not args.force:
        load = os.getloadavg()[0]
        if load > HW:
            sys.exit(f"load average {load:.1f} is above {HW}; wait or pass --force")

    goose = tc.find_goose(args.exe)
    ccs = tc.find_ccs()
    if not ccs:
        sys.exit("no C toolchain found")
    ccname = args.cc or ("clang" if "clang" in ccs else next(iter(ccs)))
    cc = ccs[ccname]
    GEN.mkdir(parents=True, exist_ok=True)
    builder = Builder(goose, cc, None)

    # Build everything first, in parallel; nothing runs while anything builds.
    jobs = []
    for b in benches:
        if not b.make:
            continue
        for v in b.values:
            meta = {"id": b.id, "title": b.title, "param": b.param, "value": v}
            prog = b.make(v)
            name = f"{b.id}_{v}"
            jobs.append((b.id, v, "timed", name,
                         prog.render(meta, False, target, batches), prog.defines))
            if not args.no_check:
                jobs.append((b.id, v, "check", name + "_check",
                             prog.render(meta, True, target, batches), prog.defines))
    print(f"building {len(jobs)} Goose programs with {cc.desc}...", flush=True)
    built = {}
    with concurrent.futures.ThreadPoolExecutor(args.jobs) as ex:
        futs = {ex.submit(builder.goose_program, j[3], j[4], j[5]): j for j in jobs}
        for fu in concurrent.futures.as_completed(futs):
            bid, v, kind, name, _, _ = futs[fu]
            exe, err = fu.result()
            built[(bid, v, kind)] = (exe, err)
            if err:
                print(f"  {name}: {err}", flush=True)
    bases = {}
    if not args.no_baselines:
        print("building baselines...", flush=True)
        bases = builder.baselines(("c", "cpp", "rs"))
        for l, exe in bases.items():
            if not exe:
                print(f"  {LANG_NAMES[l]} baseline did not build, see bench/gen/spawn/base_{l}.log")

    # Merge into earlier results, so a --only run refreshes just its rows.
    results = json.loads(rpath.read_text()) if rpath.exists() else {"points": {}, "fits": {}}
    results["meta"] = {"cpu": tc.cpu_name(), "cores": HW,
                       "os": f"{platform.system()} {platform.release()}",
                       "cc": cc.desc, "date": datetime.now().strftime("%Y-%m-%d %H:%M"),
                       "quick": args.quick}

    for b in benches:
        print(f"{b.id}: {b.title}", flush=True)
        pts = results["points"].setdefault(b.id, {})
        for v in b.values:
            p = {}
            label = f"{b.id} {b.param}={b.fmt(v)}"
            if b.make:
                exe, err = built.get((b.id, v, "check"), (None, None))
                if exe:
                    r = tc.run_measured(exe)
                    p["check"] = "ok" if r.code == 0 and "check ok" in r.out else "FAIL"
                    if p["check"] != "ok":
                        print(f"  {label}: check FAILED: {(r.out + r.err)[-200:]}", flush=True)
                elif err:
                    p["check"] = "build failed"
                exe, err = built[(b.id, v, "timed")]
                if exe and p.get("check") != "FAIL":
                    p["goose"] = run_point(exe, [], label)
                else:
                    p["goose"] = {"error": err or "check failed"}
            if b.baseline and bases:
                mode, a, bb = b.baseline(v)
                for l in b.langs:
                    if bases.get(l):
                        p[l] = run_point(bases[l], [mode, a, bb, target, batches], f"{label} {l}")
            pts[str(v)] = p
            g = p.get("goose") or {}
            bl = "  ".join(f"{l} {fmt_cell(p.get(l))}" for l in b.langs if p.get(l))
            print(f"  {b.param}={b.fmt(v):>8}  goose {fmt_cell(g) if b.make else '-':>10}  {bl}",
                  flush=True)
        if b.fit:
            xs, ys = [], []
            for v in b.values:
                g = pts.get(str(v), {}).get("goose")
                if g and "median" in g:
                    xs.append(b.fitx(v) if b.fitx else v)
                    ys.append(g["median"])
            f = fit_line(xs, ys)
            if f:
                results["fits"][b.id] = f
        tc.write_text(rpath, json.dumps(results, indent=1))

    render(results, plan(), HERE / "results.md")
    print(f"wrote {HERE / 'results.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
