// Goose compiler — driver. Includes establish the project-wide header order.

#include "includes.h"
#include "utils.h"
#include "lexer.h"
#include "ast.h"
#include "dump.h"
#include "clone.h"
#include "parser.h"
#include "resolve.h"
#include "builtins.h"
#include "typecheck_cycles.h"
#include "typecheck.h"
#include "optimize.h"
#include "optimize_basecase.h"
#include "optimize_tre.h"
#include "bce.h"
#include "codegen.h"
#include "runtime_inline.h"

namespace goose {

string DirOf(const string &path) {
    auto pos = path.find_last_of("/\\");
    return pos == string::npos ? "" : path.substr(0, pos + 1);
}

static bool FileExists(const string &path) {
    auto f = fopen(path.c_str(), "rb");
    if (f) fclose(f);
    return f != nullptr;
}

// Where the standard library lives (§11.1): an explicit --stdlib or
// GOOSE_STDLIB, else the `stdlib/` directory of the source tree the compiler
// was built in, found by walking up from the executable.
string gs_stdlibdir;
string gs_argv0;
vector<string> StdlibDirs() {
    vector<string> dirs;
    if (!gs_stdlibdir.empty()) dirs.push_back(cat(gs_stdlibdir, "/"));
    if (auto env = getenv("GOOSE_STDLIB")) dirs.push_back(cat(env, "/"));
    auto exedir = DirOf(gs_argv0);
    dirs.push_back(cat(exedir, "stdlib/"));
    dirs.push_back(cat(exedir, "../stdlib/"));
    dirs.push_back(cat(exedir, "../../stdlib/"));
    dirs.push_back(cat(exedir, "../../../stdlib/"));
    dirs.push_back("stdlib/");
    return dirs;
}

// Parses a root file and, transitively, everything it imports (each file once).
// `import a.b;` resolves relative to the root file's directory, then in the
// standard library; `import .a.b;` relative to the importing file's.
void ParseProgram(Ast &ast, const string &rootpath) {
    auto rootdir = DirOf(rootpath);
    vector<string> queue = { rootpath };
    set<string> loaded = { rootpath };
    while (!queue.empty()) {
        auto path = queue.back();
        queue.pop_back();
        auto contents = make_unique<string>();
        if (!LoadFile(path, *contents))
            throw CompileError { cat("cannot open file: ", path) };
        auto fileidx = (int)ast.sources.size();
        ast.sources.emplace_back(path, std::move(contents));
        auto &[filename, source] = ast.sources.back();
        Parser parser(ast, filename, source->c_str(), fileidx);
        parser.ParseTop();
        for (auto &imp : parser.imports) {
            auto imppath = cat(imp.relative ? DirOf(path) : rootdir, imp.path, ".goose");
            if (!imp.relative && !FileExists(imppath)) {
                for (auto &dir : StdlibDirs()) {
                    auto cand = cat(dir, imp.path, ".goose");
                    if (FileExists(cand)) { imppath = cand; break; }
                }
            }
            if (loaded.insert(imppath).second) queue.push_back(imppath);
        }
    }
    ResolveTypeNames(ast);
}

void DumpTokens(const string &path) {
    string contents;
    if (!LoadFile(path, contents)) throw CompileError { cat("cannot open file: ", path) };
    Lexer lex(path, contents.c_str());
    string s;
    while (lex.tok != T_EOF) {
        Append(s, TName(lex.tok));
        switch (lex.tok) {
            case T_IDENT:  Append(s, " ", lex.attr); break;
            case T_INTLIT: Append(s, " ", lex.ival, " (", lex.attr, ")"); break;
            case T_FLTLIT: Append(s, " ", lex.fval); break;
            case T_STRLIT: s += " "; EscapeString(s, lex.sval, '"'); break;
            default: break;
        }
        s += "\n";
        lex.Next();
    }
    fputs(s.c_str(), stdout);
}

// The runtime C sources embedded into the compiler (runtime_inline.h) and
// prepended to every generated file, in order.
static const char *runtimefiles[] = { "runtime.h", "runtime_threads.h" , "runtime_os.h" };

// Locates the src/runtime/ directory (only needed by --gen-runtime-header):
// an explicit env override, next to the executable, or relative to it in the
// source tree layout.
string FindRuntimeDir(const char *argv0) {
    vector<string> cands;
    if (auto env = getenv("GOOSE_RUNTIME")) cands.push_back(cat(env, "/"));
    auto exedir = DirOf(argv0);
    cands.push_back(cat(exedir, "runtime/"));
    cands.push_back(cat(exedir, "../../src/runtime/"));
    cands.push_back(cat(exedir, "../src/runtime/"));
    cands.push_back("src/runtime/");
    for (auto &dir : cands) {
        string probe;
        if (LoadFile(cat(dir, runtimefiles[0]), probe)) return dir;
    }
    throw CompileError { "cannot locate the runtime sources (src/runtime); "
                         "set GOOSE_RUNTIME" };
}

// Regenerates src/runtime_inline.h from src/runtime/, so the compiler binary
// is self-contained. Anyone editing the runtime re-runs this and rebuilds.
void GenRuntimeHeader(const char *argv0) {
    auto dir = FindRuntimeDir(argv0);
    string out = "// Generated by `goose --gen-runtime-header` from src/runtime/. "
                 "Do not edit.\n#pragma once\n\nnamespace goose {\n\n"
                 "struct RuntimeFile {\n    const char *name;\n    string_view text;\n"
                 "};\n\ninline const RuntimeFile runtime_files[] = {\n";
    for (auto rf : runtimefiles) {
        string src;
        if (!LoadFile(cat(dir, rf), src))
            throw CompileError { cat("cannot read runtime file: ", dir, rf) };
        if (src.find(")GSRT\"") != string::npos)
            throw CompileError { cat(rf, " contains the raw-string delimiter )GSRT\"") };
        Append(out, "    { \"", rf, "\", string_view(\n");
        // Chunked adjacent raw strings: MSVC caps single literals at ~16K.
        size_t pos = 0;
        while (pos < src.size()) {
            auto end = std::min(pos + 8000, src.size());
            if (end < src.size()) {
                auto nl = src.rfind('\n', end);
                if (nl != string::npos && nl > pos) end = nl + 1;
            }
            Append(out, "R\"GSRT(", string_view(src).substr(pos, end - pos), ")GSRT\"\n");
            pos = end;
        }
        if (src.empty()) out += "\"\"\n";
        out += "    ) },\n";
    }
    out += "};\n\n}  // namespace goose\n";
    auto path = cat(dir, "../runtime_inline.h");
    auto f = fopen(path.c_str(), "wb");
    if (!f) throw CompileError { cat("cannot write ", path) };
    fwrite(out.data(), 1, out.size(), f);
    fclose(f);
    printf("wrote %s (%d bytes)\n", path.c_str(), (int)out.size());
}

int Main(int argc, char **argv) {
    gs_argv0 = argv[0];
    string filename, outfile;
    auto dump = false, tokens = false, parseonly = false, specs = false, nocgen = false;
    auto nobce = false, bcetest = false, norfcheck = false;
    auto optlevel = 1;
    for (int i = 1; i < argc; i++) {
        string arg = argv[i];
        if (arg == "--dump") dump = true;
        else if (arg == "--tokens") tokens = true;
        else if (arg == "--parse") parseonly = true;
        else if (arg == "--specs") specs = true;
        else if (arg == "--check") nocgen = true;
        else if (arg == "--no-bce") nobce = true;
        else if (arg == "--bce-test") bcetest = true;
        // Unsound; a measurement aid only (see CodeGen::norfcheck).
        else if (arg == "--unsafe-no-rf-check") norfcheck = true;
        else if (arg == "--gen-runtime-header") { GenRuntimeHeader(argv[0]); return 0; }
        else if (arg == "-O0") optlevel = 0;
        else if (arg == "-O1") optlevel = 1;
        else if (arg == "-O2") optlevel = 2;
        else if (arg == "-o" && i + 1 < argc) outfile = argv[++i];
        else if (arg == "--include" && i + 1 < argc) gs_includes.push_back(argv[++i]);
        else if (arg == "--stdlib" && i + 1 < argc) gs_stdlibdir = argv[++i];
        else if (!arg.empty() && arg[0] == '-') {
            fprintf(stderr, "unknown option: %s\n", arg.c_str());
            return 1;
        }
        else if (filename.empty()) filename = arg;
        else { fprintf(stderr, "multiple input files given\n"); return 1; }
    }
    if (filename.empty()) {
        fprintf(stderr, "usage: goose [--dump] [--parse] [--tokens] [--specs] [--check] "
                        "[--no-bce] [--bce-test] [--unsafe-no-rf-check] [-O0|-O1|-O2] "
                        "[-o out.c] [--include header.h]... [--stdlib dir] file.goose | --gen-runtime-header\n");
        return 1;
    }
    try {
        if (tokens) {
            DumpTokens(filename);
            return 0;
        }
        Ast ast;
        ParseProgram(ast, filename);
        if (dump) {
            // Dump is parse-level output: no typecheck, so parse-only test
            // files can roundtrip.
            string s;
            ast.Dump(s);
            fputs(s.c_str(), stdout);
            return 0;
        }
        if (parseonly) {
            printf("parsed ok: %d top-level declarations, %d file(s)\n",
                   (int)ast.topdecls.size(), (int)ast.sources.size());
            return 0;
        }
        TypeCheckProgram(ast);
        Optimizer opt(ast, optlevel);
        if (specs) {
            string s;
            opt.DumpSpecs(s);
            fputs(s.c_str(), stdout);
        }
        printf("typechecked ok: %d specialization(s), %d struct/%d enum instance(s); "
               "optimized -O%d: %d inlined, %d base case(s), %d folded, %d propagated, "
               "%d tail loop(s)\n",
               (int)ast.fnspecs.size(), (int)ast.structinsts.size(),
               (int)ast.enuminsts.size(), optlevel, opt.inlined, opt.basecases,
               opt.folded, opt.propagated, opt.tailloops);
        BCE bce(ast);
        if (!nobce) {
            bce.RunAll();
            printf("bce: elided %d/%d index and %d/%d slice checks\n",
                   bce.idxelided, bce.idxtotal, bce.slelided, bce.sltotal);
        }
        if (bcetest) {
            auto fails = bce.VerifyAnnotations();
            if (fails) {
                fprintf(stderr, "bce-test: %d annotation failure(s)\n", fails);
                return 1;
            }
            printf("bce-test: all annotations verified\n");
        }
        if (nocgen) return 0;
        // The extern-support runtime is written against the generated types,
        // so codegen splices it in after them rather than up front.
        for (auto &rf : runtime_files)
            if (string_view(rf.name) == "runtime_os.h") gs_runtime_os_text = string(rf.text);
        CodeGen cg(ast, norfcheck);
        // Assemble: compiler-set feature defines, the embedded runtime, then
        // the generated program.
        string out = cat("/* Generated by the Goose compiler from ", filename,
                         ". Do not edit. */\n\n", cg.predefs);
        for (auto &rf : runtime_files) {
            if (string_view(rf.name) == "runtime_os.h") continue;
            Append(out, "/* ==== ", rf.name, " ==== */\n", rf.text, "\n");
        }
        out += cg.result;
        if (outfile.empty()) {
            auto dot = filename.find_last_of('.');
            outfile = cat(dot == string::npos ? filename : filename.substr(0, dot), ".c");
        }
        auto f = fopen(outfile.c_str(), "wb");
        if (!f) throw CompileError { cat("cannot write output file: ", outfile) };
        fwrite(out.data(), 1, out.size(), f);
        fclose(f);
        printf("wrote %s (%d bytes)\n", outfile.c_str(), (int)out.size());
    } catch (CompileError &e) {
        fprintf(stderr, "%s\n", e.msg.c_str());
        return 1;
    }
    return 0;
}

}  // namespace goose

int main(int argc, char **argv) {
    #ifdef _MSC_VER
        // Asserts and aborts go to stderr and exit, never a dialog, so failing
        // debug runs terminate cleanly under test automation.
        _set_abort_behavior(0, _WRITE_ABORT_MSG | _CALL_REPORTFAULT);
        _CrtSetReportMode(_CRT_ASSERT, _CRTDBG_MODE_FILE);
        _CrtSetReportFile(_CRT_ASSERT, _CRTDBG_FILE_STDERR);
        _CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_FILE);
        _CrtSetReportFile(_CRT_ERROR, _CRTDBG_FILE_STDERR);
    #endif
    return goose::Main(argc, argv);
}
