// Generated by `goose --gen-runtime-header` from src/runtime/. Do not edit.
#pragma once

namespace goose {

struct RuntimeFile {
    const char *name;
    string_view text;
};

inline const RuntimeFile runtime_files[] = {
    { "runtime.h", string_view(
R"GSRT(/* Goose runtime — prepended verbatim to every compiler-generated C file.
   Plain C99 (+ #pragma pack, unaligned scalar access); compiles with MSVC,
   gcc, clang, and tcc. Kept deliberately small: per-operation behavior (push,
   indexing, field access) is emitted inline by the compiler; only genuinely
   shared machinery lives here (data stacks, varints, printing, aborts,
   threads/queues in runtime_threads.h). */

/* The OS layer (runtime_os.h) opens files on Windows with _wfopen, which the
   Microsoft CRT deprecates in favour of its own _s variant. */
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS 1
#endif

#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#ifndef GS_NEED_THREADS
#define GS_NEED_THREADS 0
#endif
#ifndef GS_DEBUG
#define GS_DEBUG 0          /* 1: overflow, `as` range, and tag checks (§9.3). */
#endif

/* Configuration; all overridable from the compile command line. */
#ifndef GS_MAX_STACKS
#define GS_MAX_STACKS 1024          /* Data stacks per thread program. */
#endif
#ifndef GS_STACK_RESERVE
#define GS_STACK_RESERVE (256ull << 20)  /* Address space reserved per stack. */
#endif
#ifndef GS_STACK_GAP
#define GS_STACK_GAP (1ull << 20)   /* Unmapped tail so runaway growth aborts. */
#endif
/* §10.4 caps a stack reservation at 2^48 bytes, which is what lets the
   compiler treat every size, count and index as fitting in 48 bits: the
   guard region enforces it, so no growth path needs its own check. */
#if GS_STACK_RESERVE > (1ull << 48)
#error "GS_STACK_RESERVE exceeds the 2^48 limit (goose_spec.md 10.4)"
#endif
/* Every data stack has the same usable reservation and trailing guard gap. */
#define GS_REGION_SIZE ((size_t)GS_STACK_RESERVE + (size_t)GS_STACK_GAP)

#ifdef _MSC_VER
#define GS_NORETURN __declspec(noreturn)
#define GS_NOINLINE __declspec(noinline)
#else
#define GS_NORETURN __attribute__((noreturn))
#define GS_NOINLINE __attribute__((noinline))
#endif

#if GS_NEED_THREADS
#ifdef _MSC_VER
#define GS_TLS __declspec(thread)
#else
#define GS_TLS __thread
#endif
#else
#define GS_TLS
#endif

/* ---------------------------------------------------------------------------
   Aborts (§9.3). Not catchable; message + nonzero exit. Compiler-emitted
   checks carry an error id plus a file (a static string in the generated
   code) and line; runtime-internal failures use gs_panic. The int64_t
   returns let checks sit inside expressions. */

enum {
    GS_E_CAPACITY,     /* limited array capacity exceeded */
    GS_E_SLICE,        /* slice bounds out of range */
    GS_E_RELOFF,       /* relative reference offset overflow */
    GS_E_ASSERT,       /* assert failed */
    GS_E_CAPRANGE,     /* invalid capacity */
    GS_E_RESIZEFILL,   /* resize growth requires a fill value */
    GS_E_RESIZENEG,    /* resize to a negative length */
    GS_E_POP,          /* pop on empty array */
    GS_E_THREADID,     /* thread_wait on an unknown thread id */
    GS_E_THREADSELF,   /* a worker cannot wait for itself */
    GS_E_TAG,          /* corrupt ADT tag (debug builds only) */
    GS_E_ENDIAN,       /* serialization on a big-endian host */
    GS_E_SLICELEN,     /* slice pool length negative or beyond any data stack */
    GS_E_POOLSLICE,    /* a slice handed to a slice pool is not one of its runs */
    GS_E_RELNULL,      /* a non-null optional self-relative target has offset zero */
    GS_E_STACKS,       /* a function needs more data stacks than GS_MAX_STACKS */
};

static const char *gs_errmsgs[] = {
    "limited array capacity exceeded",
    "slice bounds out of range",
    "relative reference offset overflow",
    "assert failed",
    "invalid capacity",
    "resize growth requires a fill value",
    "resize to a negative length",
    "pop on empty array",
    "thread_wait on an unknown thread id",
    "thread_wait on the current thread",
    "corrupt ADT tag",
    "serialization needs a little-endian host (not supported yet)",
    "invalid slice length",
    "slice not from this pool",
    "non-null relative reference encodes as null",
    "too many data stacks (deep call nesting?)",
};

static GS_NORETURN void gs_panic(const char *msg) {
    fprintf(stderr, "goose runtime error: %s\n", msg);
    exit(1);
}

static GS_NORETURN void gs_abort(int err, const char *file, int line) {
    fprintf(stderr, "goose runtime error: %s (%s:%d)\n", gs_errmsgs[err], file, line);
    exit(1);
}

/* The program's own abort(msg) (§9.3): the message is Goose bytes, not a C
   string, so it goes out with an explicit length. */
static GS_NORETURN void gs_abort_msg(const uint8_t *msg, int64_t len, const char *file,
                                     int line) {
    fputs("goose runtime error: ", stderr);
    fwrite(msg, 1, (size_t)len, stderr);
    fprintf(stderr, " (%s:%d)\n", file, line);
    exit(1);
}

static GS_NORETURN void gs_exit(int64_t code) {
    fflush(stdout);
    exit((int)code);
}

static int64_t gs_idxfail(int64_t i, int64_t n, const char *file, int line) {
    fprintf(stderr, "goose runtime error: index %lld out of bounds (length %lld) "
            "(%s:%d)\n", (long long)i, (long long)n, file, line);
    exit(1);
}

/* Bounds check as one unsigned compare; the index operand must be side-effect
   free (the compiler guarantees this at emission). */
#define GS_IDX(i, n, f, l) \
    ((uint64_t)(i) < (uint64_t)(n) ? (i) : gs_idxfail((int64_t)(i), (n), (f), (l)))

/* Statically unreachable spots (e.g. an ADT tag no variant matches): checked
   in debug builds, an optimizer hint in release. */
#if GS_DEBUG
#define GS_UNREACHABLE(f, l) gs_abort(GS_E_TAG, (f), (l))
#elif defined(_MSC_VER)
#define GS_UNREACHABLE(f, l) __assume(0)
#elif defined(__GNUC__)
#define GS_UNREACHABLE(f, l) __builtin_unreachable()
#else
#define GS_UNREACHABLE(f, l) ((void)0)
#endif

/* memcpy and memcmp for a slice's elements. An empty slice's data pointer is
   NULL where the slice was zero-filled (default<T>(), a default element),
   and C leaves both undefined on a null pointer even for zero bytes. */
static void gs_memcpy(void *dst, const void *src, size_t n) {
    if (n) memcpy(dst, src, n);
}

static int gs_memcmp(const void *a, const void *b, size_t n) {
    return n ? memcmp(a, b, n) : 0;
}

/* ---------------------------------------------------------------------------
   Integer semantics (§6.2): every operation runs at its operands' type. The
   operations compute wide (so wrap is defined in C), truncate back, and — when
   the generated C is compiled with -DGS_DEBUG=1 — abort when the wide result
   does not fit the type. Shifts mask their count to the width; division is
   zero-checked always.

   Only division and modulo check anything in a release build, so only they
   need to be functions there; everything else is a macro whose body is the
   expression the release function would have returned. An optimizing backend
   inlines either form to the same instruction, but a backend that does not
   inline (libtcc, or any -O0 build) would otherwise pay a call for every
   arithmetic operation in the program — which measured as 13-37% of total
   runtime across the benchmarks.

   The signed types' add, sub, mul and neg also take the file and line of the
   operation, for the debug build's overflow message; the release macros
   drop them unevaluated. */

#if GS_DEBUG
static GS_NORETURN void gs_ovf(int64_t a, const char *op, int64_t b, const char *type,
                               const char *file, int line) {
    fprintf(stderr, "goose runtime error: integer overflow (debug): %lld %s %lld at %s "
            "(%s:%d)\n", (long long)a, op, (long long)b, type, file, line);
    exit(1);
}
static GS_NORETURN void gs_ovf_neg(int64_t a, const char *type, const char *file, int line) {
    fprintf(stderr, "goose runtime error: integer overflow (debug): -(%lld) at %s (%s:%d)\n",
            (long long)a, type, file, line);
    exit(1);
}
)GSRT"
R"GSRT(#define GS_OVFCHK(r, MIN, MAX, a, op, b, type, file, line) \
    do { if ((r) < (MIN) || (r) > (MAX)) gs_ovf((a), (op), (b), (type), (file), (line)); } while (0)
#else
#define GS_OVFCHK(r, MIN, MAX, a, op, b, type, file, line) ((void)0)
#endif

static GS_NORETURN void gs_divfail(const char *file, int line) {
    fprintf(stderr, "goose runtime error: division by zero (%s:%d)\n", file, line);
    exit(1);
}

/* Division and modulo, both builds: the zero check is not optional, and `%`
   is Euclidean. */
#define GS_DIVOPS_S(SFX, T, MIN, MAX) \
static T gs_div_##SFX(T a, T b, const char *file, int line) { \
    if (b == 0) gs_divfail(file, line); \
    int64_t r = (int64_t)a / (int64_t)b; \
    GS_OVFCHK(r, MIN, MAX, a, "/", b, #SFX, file, line); \
    return (T)r; } \
static T gs_mod_##SFX(T a, T b, const char *file, int line) { \
    if (b == 0) gs_divfail(file, line); \
    int64_t r = (int64_t)a % (int64_t)b; \
    if (r < 0) r += (int64_t)b < 0 ? -(int64_t)b : (int64_t)b; \
    return (T)r; }

#define GS_DIVOPS_U(SFX, T) \
static T gs_div_##SFX(T a, T b, const char *file, int line) { \
    if (b == 0) gs_divfail(file, line); \
    return (T)(a / b); } \
static T gs_mod_##SFX(T a, T b, const char *file, int line) { \
    if (b == 0) gs_divfail(file, line); \
    return (T)(a % b); }

GS_DIVOPS_S(i8, int8_t, -128, 127)
GS_DIVOPS_S(i16, int16_t, -32768, 32767)
GS_DIVOPS_S(i32, int32_t, INT32_MIN, INT32_MAX)
GS_DIVOPS_U(u8, uint8_t)
GS_DIVOPS_U(u16, uint16_t)
GS_DIVOPS_U(u32, uint32_t)

#if GS_DEBUG

/* Signed narrow types (8/16/32 bits): 64-bit signed math covers every
   intermediate result. */
#define GS_INTOPS_S(SFX, T, MIN, MAX, BITS) \
static T gs_add_##SFX(T a, T b, const char *file, int line) { \
    int64_t r = (int64_t)a + (int64_t)b; \
    if (r < MIN || r > MAX) gs_ovf(a, "+", b, #SFX, file, line); \
    return (T)r; } \
static T gs_sub_##SFX(T a, T b, const char *file, int line) { \
    int64_t r = (int64_t)a - (int64_t)b; \
    if (r < MIN || r > MAX) gs_ovf(a, "-", b, #SFX, file, line); \
    return (T)r; } \
static T gs_mul_##SFX(T a, T b, const char *file, int line) { \
    int64_t r = (int64_t)a * (int64_t)b; \
    if (r < MIN || r > MAX) gs_ovf(a, "*", b, #SFX, file, line); \
    return (T)r; } \
static T gs_neg_##SFX(T a, const char *file, int line) { \
    int64_t r = -(int64_t)a; \
    if (r < MIN || r > MAX) gs_ovf_neg(a, #SFX, file, line); \
    return (T)r; } \
static T gs_shl_##SFX(T a, int64_t n) { \
    return (T)((uint64_t)a << (n & (BITS - 1))); } \
static T gs_shr_##SFX(T a, int64_t n) { \
    return (T)((int64_t)a >> (n & (BITS - 1))); }

/* Unsigned types wrap modulo 2^width by definition (§6.2) in every build:
   plain C unsigned arithmetic, truncated back to the width. */
#define GS_INTOPS_U(SFX, T, MAX, BITS) \
static T gs_add_##SFX(T a, T b) { return (T)(a + b); } \
static T gs_sub_##SFX(T a, T b) { return (T)(a - b); } \
static T gs_mul_##SFX(T a, T b) { return (T)((uint64_t)a * (uint64_t)b); } \
static T gs_shl_##SFX(T a, int64_t n) { \
    return (T)((uint64_t)a << (n & (BITS - 1))); } \
static T gs_shr_##SFX(T a, int64_t n) { \
    return (T)((uint64_t)a >> (n & (BITS - 1))); }

GS_INTOPS_S(i8,  int8_t,  -128, 127, 8)
GS_INTOPS_S(i16, int16_t, -32768, 32767, 16)
GS_INTOPS_S(i32, int32_t, INT32_MIN, INT32_MAX, 32)
GS_INTOPS_U(u8,  uint8_t,  255u, 8)
GS_INTOPS_U(u16, uint16_t, 65535u, 16)
GS_INTOPS_U(u32, uint32_t, 4294967295u, 32)

/* The 64-bit types detect overflow on the value itself. */
static int64_t gs_add_i64(int64_t a, int64_t b, const char *file, int line) {
    int64_t r = (int64_t)((uint64_t)a + (uint64_t)b);
    if (((a ^ r) & (b ^ r)) < 0) gs_ovf(a, "+", b, "i64", file, line);
    return r;
}
static int64_t gs_sub_i64(int64_t a, int64_t b, const char *file, int line) {
    int64_t r = (int64_t)((uint64_t)a - (uint64_t)b);
    if (((a ^ b) & (a ^ r)) < 0) gs_ovf(a, "-", b, "i64", file, line);
    return r;
}
static int64_t gs_mul_i64(int64_t a, int64_t b, const char *file, int line) {
    int64_t r = (int64_t)((uint64_t)a * (uint64_t)b);
    if (a && b &&
        ((a == -1 && b == INT64_MIN) || (b == -1 && a == INT64_MIN) || r / b != a))
        gs_ovf(a, "*", b, "i64", file, line);
    return r;
}
static int64_t gs_neg_i64(int64_t a, const char *file, int line) {
    if (a == INT64_MIN) gs_ovf_neg(a, "i64", file, line);
    return (int64_t)(0u - (uint64_t)a);
}
static int64_t gs_shl_i64(int64_t a, int64_t n) {
    return (int64_t)((uint64_t)a << (n & 63));
}
static int64_t gs_shr_i64(int64_t a, int64_t n) { return a >> (n & 63); }
static uint64_t gs_add_u64(uint64_t a, uint64_t b) { return a + b; }
static uint64_t gs_sub_u64(uint64_t a, uint64_t b) { return a - b; }
static uint64_t gs_mul_u64(uint64_t a, uint64_t b) { return a * b; }
static uint64_t gs_shl_u64(uint64_t a, int64_t n) { return a << (n & 63); }
static uint64_t gs_shr_u64(uint64_t a, int64_t n) { return a >> (n & 63); }

#else  /* release: each operation is the expression the function returned */

#define gs_add_i8(a, b, f, l)  ((int8_t)((int64_t)(a) + (int64_t)(b)))
#define gs_sub_i8(a, b, f, l)  ((int8_t)((int64_t)(a) - (int64_t)(b)))
#define gs_mul_i8(a, b, f, l)  ((int8_t)((int64_t)(a) * (int64_t)(b)))
#define gs_neg_i8(a, f, l)     ((int8_t)(-(int64_t)(a)))
#define gs_shl_i8(a, n)  ((int8_t)((uint64_t)(a) << ((n) & 7)))
#define gs_shr_i8(a, n)  ((int8_t)((int64_t)(a) >> ((n) & 7)))

#define gs_add_i16(a, b, f, l) ((int16_t)((int64_t)(a) + (int64_t)(b)))
#define gs_sub_i16(a, b, f, l) ((int16_t)((int64_t)(a) - (int64_t)(b)))
#define gs_mul_i16(a, b, f, l) ((int16_t)((int64_t)(a) * (int64_t)(b)))
#define gs_neg_i16(a, f, l)    ((int16_t)(-(int64_t)(a)))
#define gs_shl_i16(a, n) ((int16_t)((uint64_t)(a) << ((n) & 15)))
#define gs_shr_i16(a, n) ((int16_t)((int64_t)(a) >> ((n) & 15)))

#define gs_add_i32(a, b, f, l) ((int32_t)((int64_t)(a) + (int64_t)(b)))
#define gs_sub_i32(a, b, f, l) ((int32_t)((int64_t)(a) - (int64_t)(b)))
#define gs_mul_i32(a, b, f, l) ((int32_t)((int64_t)(a) * (int64_t)(b)))
#define gs_neg_i32(a, f, l)    ((int32_t)(-(int64_t)(a)))
#define gs_shl_i32(a, n) ((int32_t)((uint64_t)(a) << ((n) & 31)))
#define gs_shr_i32(a, n) ((int32_t)((int64_t)(a) >> ((n) & 31)))

#define gs_add_u8(a, b)  ((uint8_t)((a) + (b)))
#define gs_sub_u8(a, b)  ((uint8_t)((a) - (b)))
#define gs_mul_u8(a, b)  ((uint8_t)((uint64_t)(a) * (uint64_t)(b)))
#define gs_shl_u8(a, n)  ((uint8_t)((uint64_t)(a) << ((n) & 7)))
#define gs_shr_u8(a, n)  ((uint8_t)((uint64_t)(a) >> ((n) & 7)))

#define gs_add_u16(a, b) ((uint16_t)((a) + (b)))
#define gs_sub_u16(a, b) ((uint16_t)((a) - (b)))
#define gs_mul_u16(a, b) ((uint16_t)((uint64_t)(a) * (uint64_t)(b)))
#define gs_shl_u16(a, n) ((uint16_t)((uint64_t)(a) << ((n) & 15)))
#define gs_shr_u16(a, n) ((uint16_t)((uint64_t)(a) >> ((n) & 15)))

#define gs_add_u32(a, b) ((uint32_t)((a) + (b)))
#define gs_sub_u32(a, b) ((uint32_t)((a) - (b)))
#define gs_mul_u32(a, b) ((uint32_t)((uint64_t)(a) * (uint64_t)(b)))
#define gs_shl_u32(a, n) ((uint32_t)((uint64_t)(a) << ((n) & 31)))
#define gs_shr_u32(a, n) ((uint32_t)((uint64_t)(a) >> ((n) & 31)))

#define gs_add_i64(a, b, f, l) ((int64_t)((uint64_t)(a) + (uint64_t)(b)))
#define gs_sub_i64(a, b, f, l) ((int64_t)((uint64_t)(a) - (uint64_t)(b)))
#define gs_mul_i64(a, b, f, l) ((int64_t)((uint64_t)(a) * (uint64_t)(b)))
#define gs_neg_i64(a, f, l)    ((int64_t)(0u - (uint64_t)(a)))
#define gs_shl_i64(a, n) ((int64_t)((uint64_t)(a) << ((n) & 63)))
#define gs_shr_i64(a, n) ((int64_t)((a) >> ((n) & 63)))

#define gs_add_u64(a, b) ((uint64_t)((a) + (b)))
#define gs_sub_u64(a, b) ((uint64_t)((a) - (b)))
#define gs_mul_u64(a, b) ((uint64_t)((a) * (b)))
#define gs_shl_u64(a, n) ((uint64_t)((a) << ((n) & 63)))
#define gs_shr_u64(a, n) ((uint64_t)((a) >> ((n) & 63)))

#endif  /* GS_DEBUG */

/* 64-bit division and modulo. Division overflow (i64.min / -1) would trap in
   hardware and aborts in every build. */
)GSRT"
R"GSRT(static int64_t gs_div_i64(int64_t a, int64_t b, const char *file, int line) {
    if (b == 0) gs_divfail(file, line);
    if (a == INT64_MIN && b == -1) {
        fprintf(stderr, "goose runtime error: integer overflow in division (%s:%d)\n",
                file, line);
        exit(1);
    }
    return a / b;
}
static int64_t gs_mod_i64(int64_t a, int64_t b, const char *file, int line) {
    if (b == 0) gs_divfail(file, line);
    if (b == -1) return 0;   /* Exactly 0, and i64.min % -1 would trap. */
    int64_t r = a % b;
    /* |b| unsigned, so a divisor of i64.min (unrepresentable negated) works. */
    if (r < 0) r = (int64_t)((uint64_t)r + (b < 0 ? 0u - (uint64_t)b : (uint64_t)b));
    return r;
}
static uint64_t gs_div_u64(uint64_t a, uint64_t b, const char *file, int line) {
    if (b == 0) gs_divfail(file, line);
    return a / b;
}
static uint64_t gs_mod_u64(uint64_t a, uint64_t b, const char *file, int line) {
    if (b == 0) gs_divfail(file, line);
    return a % b;
}

/* `as!` float-to-int: truncate toward zero, wrap modulo 2^64 (§6.3). Defined
   the same on every platform, unlike a raw C cast of an out-of-range value. */
static int64_t gs_f2iwrap(double d) {
    if (d != d) return 0;
    d = trunc(d);
    if (d >= -9223372036854775808.0 && d < 9223372036854775808.0) return (int64_t)d;
    d = fmod(d, 18446744073709551616.0);
    if (d < 0) d += 18446744073709551616.0;
    return (int64_t)(uint64_t)d;
}

/* `as` conversion checks (§6.3): abort in debug builds whenever the
   conversion would change the value, naming the value, the target type and
   the cast's file and line; identity/plain casts in release, which drop all
   three unevaluated. A conversion to f32 is a plain C cast in every build and
   has none. */
#if GS_DEBUG

static int64_t gs_fmt_f64(uint8_t *dst, double v);

/* The message of a failing check, with the source value as text. */
static GS_NORETURN void gs_asfail(const char *why, const char *num, const char *type,
                                  const char *file, int line) {
    fprintf(stderr, "goose runtime error: as conversion %s (debug): %s as %s (%s:%d)\n",
            why, num, type, file, line);
    exit(1);
}
static GS_NORETURN void gs_asfail_i(const char *why, int64_t v, const char *type,
                                    const char *file, int line) {
    char num[24];
    snprintf(num, sizeof(num), "%lld", (long long)v);
    gs_asfail(why, num, type, file, line);
}
static GS_NORETURN void gs_asfail_u(const char *why, uint64_t v, const char *type,
                                    const char *file, int line) {
    char num[24];
    snprintf(num, sizeof(num), "%llu", (unsigned long long)v);
    gs_asfail(why, num, type, file, line);
}
static GS_NORETURN void gs_asfail_f(const char *why, double d, const char *type,
                                    const char *file, int line) {
    uint8_t num[32];
    gs_fmt_f64(num, d);
    gs_asfail(why, (const char *)num, type, file, line);
}

static int64_t gs_rangechk(int64_t v, int64_t lo, int64_t hi, const char *type,
                           const char *file, int line) {
    if (v < lo || v > hi) gs_asfail_i("out of range", v, type, file, line);
    return v;
}
static uint64_t gs_rangechk_u(uint64_t v, uint64_t hi, const char *type, const char *file,
                              int line) {
    if (v > hi) gs_asfail_u("out of range", v, type, file, line);
    return v;
}
/* To a signed type or a narrower unsigned one, whose range is lo..hi. */
static int64_t gs_f2ichk(double d, int64_t lo, int64_t hi, const char *type, const char *file,
                         int line) {
    if (!(d >= -9223372036854775808.0 && d < 9223372036854775808.0))
        gs_asfail_f("out of range", d, type, file, line);
    int64_t v = (int64_t)d;
    if (v < lo || v > hi) gs_asfail_f("out of range", d, type, file, line);
    if ((double)v != d) gs_asfail_f("changes the value", d, type, file, line);
    return v;
}
static uint64_t gs_f2uchk(double d, const char *file, int line) {
    if (!(d >= 0 && d < 18446744073709551616.0))
        gs_asfail_f("out of range", d, "u64", file, line);
    uint64_t v = (uint64_t)d;
    if ((double)v != d) gs_asfail_f("changes the value", d, "u64", file, line);
    return v;
}
static double gs_i2fchk(int64_t v, const char *file, int line) {
    double d = (double)v;
    if ((int64_t)d != v || d >= 9223372036854775808.0)
        gs_asfail_i("changes the value", v, "f64", file, line);
    return d;
}
static double gs_u2fchk(uint64_t v, const char *file, int line) {
    double d = (double)v;
    if (d >= 18446744073709551616.0 || (uint64_t)d != v)
        gs_asfail_u("changes the value", v, "f64", file, line);
    return d;
}
#define GS_RANGE(v, lo, hi, t, f, l) gs_rangechk((v), (lo), (hi), (t), (f), (l))
#define GS_RANGE_U(v, hi, t, f, l)   gs_rangechk_u((v), (hi), (t), (f), (l))
#define GS_F2I(d, lo, hi, t, f, l)   gs_f2ichk((d), (lo), (hi), (t), (f), (l))
#define GS_F2U(d, f, l)              gs_f2uchk((d), (f), (l))
#define GS_I2F(v, f, l)              gs_i2fchk((v), (f), (l))
#define GS_U2F(v, f, l)              gs_u2fchk((v), (f), (l))

#else

#define GS_RANGE(v, lo, hi, t, f, l) (v)
#define GS_RANGE_U(v, hi, t, f, l)   (v)
/* Deterministic truncation in release too. */
#define GS_F2I(d, lo, hi, t, f, l)   gs_f2iwrap(d)
#define GS_F2U(d, f, l)              ((uint64_t)gs_f2iwrap(d))
#define GS_I2F(v, f, l)              ((double)(v))
#define GS_U2F(v, f, l)              ((double)(uint64_t)(v))

#endif

/* ---------------------------------------------------------------------------
   Data stacks (§1.2, Appendix C.1/C.4): large reserved regions, committed on
   use, bump-pointer allocation, watermark restore on scope exit. Emitted code
   holds them per thread program via gs_stks (index = the hidden gs_sp
   argument plus a per-function constant); globals own dedicated stacks. */

typedef struct {
    uint8_t *top;
} gs_stack;

/* The program's arguments, for stdlib/os.goose (runtime_os.h). */
static int gs_argc;
static char **gs_argv;

/* Every region owned by the current thread program, so the Windows fault
   handler can tell "commit more" from a genuine crash and guard-gap overruns
   abort with a message. Goose workers cannot access another thread's storage.
   Keeping this registry thread-local avoids both races with fault handlers
   and signal-unsafe locks when a different worker allocates or exits. */
static GS_TLS uint8_t *gs_regions[GS_MAX_STACKS * 4];
static GS_TLS volatile long gs_nregions;

#ifdef _WIN32

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>

static size_t gs_page_size = 0;
#define GS_COMMIT_CHUNK (1u << 20)
/* What each thread program keeps of its native stack for reporting that
   stack's overflow (gs_native_stack_init). */
#define GS_STACK_GUARANTEE (64u << 10)

static LONG WINAPI gs_fault_filter(EXCEPTION_POINTERS *ep) {
    DWORD code = ep->ExceptionRecord->ExceptionCode;
    if (code == EXCEPTION_STACK_OVERFLOW) {
        /* On the little stack the guarantee kept: WriteFile rather than
           stdio, which could want more. */
        static const char msg[] = "goose runtime error: native call stack overflow\n";
        DWORD written;
        WriteFile(GetStdHandle(STD_ERROR_HANDLE), msg, sizeof(msg) - 1, &written, NULL);
        ExitProcess(1);
    }
    if (code != STATUS_ACCESS_VIOLATION)
        return EXCEPTION_CONTINUE_SEARCH;
    uint8_t *hit = (uint8_t *)ep->ExceptionRecord->ExceptionInformation[1];
    for (long i = 0; i < gs_nregions; i++) {
        uint8_t *base = gs_regions[i];
        if ((uintptr_t)hit - (uintptr_t)base < GS_REGION_SIZE) {
            /* Within the usable part: commit another chunk (clamped to the
               region) and resume. Within the gap: a data stack overran. */
            if (hit < base + GS_STACK_RESERVE) {
                uint8_t *page = (uint8_t *)((size_t)hit & ~(gs_page_size - 1));
                size_t n = GS_COMMIT_CHUNK;
)GSRT"
R"GSRT(                if (page + n > base + GS_STACK_RESERVE)
                    n = (size_t)(base + GS_STACK_RESERVE - page);
                if (VirtualAlloc(page, n, MEM_COMMIT, PAGE_READWRITE))
                    return EXCEPTION_CONTINUE_EXECUTION;
            }
            fputs("goose runtime error: data stack overflow\n", stderr);
            ExitProcess(1);
        }
    }
    return EXCEPTION_CONTINUE_SEARCH;
}

/* Installed once by main, before any worker can start. */
static void gs_regions_init(void) {
    SYSTEM_INFO si;
    GetSystemInfo(&si);
    gs_page_size = si.dwPageSize;
    if (!AddVectoredExceptionHandler(1, gs_fault_filter))
        gs_panic("cannot install data stack fault handler");
}

/* Run by each thread program's thread as it starts. TinyCC's kernel32.def
   does not list SetThreadStackGuarantee, so a program it builds looks it up. */
static void gs_native_stack_init(void) {
    ULONG room = GS_STACK_GUARANTEE;
    #ifdef __TINYC__
        BOOL (WINAPI *guarantee)(PULONG) = (BOOL (WINAPI *)(PULONG))GetProcAddress(
            GetModuleHandleA("kernel32.dll"), "SetThreadStackGuarantee");
        if (guarantee) guarantee(&room);
    #else
        SetThreadStackGuarantee(&room);
    #endif
}

static void gs_native_stack_free(void) {}

static uint8_t *gs_reserve_region(void) {
    if (gs_nregions == GS_MAX_STACKS * 4)
        gs_panic("too many data stack regions");
    uint8_t *p = (uint8_t *)VirtualAlloc(0, GS_REGION_SIZE, MEM_RESERVE, PAGE_READWRITE);
    if (!p) gs_panic("cannot reserve data stack address space");
    long i = gs_nregions;
    gs_regions[i] = p;
    gs_nregions = i + 1;  /* Publish only the initialized entry. */
    return p;
}

static void gs_release_region(uint8_t *base) {
    if (!VirtualFree(base, 0, MEM_RELEASE))
        gs_panic("cannot release data stack address space");
}

#else  /* posix */

#include <sys/mman.h>
#include <unistd.h>
#include <signal.h>
#include <pthread.h>

/* The calling thread's native stack, from GS_NATIVE_SLOP below its lowest
   usable address up to its top: a fault in there is that stack overflowing,
   whether on the guard below it or at a limit the kernel would not grow it
   past. The slop covers a frame larger than the guard reaching over it.
   Empty where the platform cannot tell. */
#define GS_NATIVE_SLOP (64u << 10)
static GS_TLS uintptr_t gs_native_lo, gs_native_hi;
/* The alternate signal stack gs_native_stack_init allocated, if it did. */
static GS_TLS void *gs_sigstack;
#define GS_SIGSTACK_MIN (64u << 10)
/* What the fault handler replaced, for the faults that are not its own. */
static struct sigaction gs_prev_segv, gs_prev_bus;

static void gs_fault_handler(int sig, siginfo_t *info, void *ctx) {
    (void)ctx;
    uint8_t *hit = (uint8_t *)info->si_addr;
    for (long i = 0; i < gs_nregions; i++) {
        uint8_t *base = gs_regions[i];
        if ((uintptr_t)hit - (uintptr_t)base < GS_REGION_SIZE) {
            static const char msg[] = "goose runtime error: data stack overflow\n";
            ssize_t w = write(2, msg, sizeof(msg) - 1);
            (void)w;
            _exit(1);
        }
    }
    if ((uintptr_t)hit - gs_native_lo < gs_native_hi - gs_native_lo) {
        static const char msg[] = "goose runtime error: native call stack overflow\n";
        ssize_t w = write(2, msg, sizeof(msg) - 1);
        (void)w;
        _exit(1);
    }
    /* Not ours: the access faults again under what handled it before, the
       default action or a sanitizer's report. */
    sigaction(sig, sig == SIGSEGV ? &gs_prev_segv : &gs_prev_bus, NULL);
}

static void gs_regions_init(void) {
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = gs_fault_handler;
    /* A native stack overflow leaves the handler no room on the thread's own. */
    sa.sa_flags = SA_SIGINFO | SA_ONSTACK;
    if (sigaction(SIGSEGV, &sa, &gs_prev_segv))
        gs_panic("cannot install data stack fault handler");
    #ifdef SIGBUS
        if (sigaction(SIGBUS, &sa, &gs_prev_bus))
            gs_panic("cannot install data stack fault handler");
    #endif
}

#ifdef __linux__
/* pthread.h declares it only under _GNU_SOURCE, which would have to come
   before every system header a file includes. */
int pthread_getattr_np(pthread_t, pthread_attr_t *);
#endif

static size_t gs_sigstack_size(void) {
    return SIGSTKSZ > GS_SIGSTACK_MIN ? (size_t)SIGSTKSZ : (size_t)GS_SIGSTACK_MIN;
}

/* Run by each thread program's thread as it starts: an alternate stack for
   the fault handler, unless the thread has one (ASan gives every thread its
   own), and the bounds of the thread's stack. */
static void gs_native_stack_init(void) {
    stack_t ss;
    uintptr_t lo = 0, hi = 0;
    if (!sigaltstack(NULL, &ss) && (ss.ss_flags & SS_DISABLE)) {
        ss.ss_size = gs_sigstack_size();
        ss.ss_sp = malloc(ss.ss_size);
        ss.ss_flags = 0;
        if (ss.ss_sp && !sigaltstack(&ss, NULL)) gs_sigstack = ss.ss_sp;
        else free(ss.ss_sp);
    }
    #if defined(__APPLE__)
        hi = (uintptr_t)pthread_get_stackaddr_np(pthread_self());
        lo = hi - pthread_get_stacksize_np(pthread_self());
    #elif defined(__linux__)
        pthread_attr_t attr;
        void *base;
        size_t size;
        if (!pthread_getattr_np(pthread_self(), &attr)) {
            if (!pthread_attr_getstack(&attr, &base, &size)) {
                lo = (uintptr_t)base;
                hi = lo + size;
            }
            pthread_attr_destroy(&attr);
        }
    #endif
    if (lo > GS_NATIVE_SLOP) {
        gs_native_lo = lo - GS_NATIVE_SLOP;
        gs_native_hi = hi;
    }
}

/* At a worker's end, the alternate stack gs_native_stack_init gave it. */
static void gs_native_stack_free(void) {
    stack_t ss;
    if (!gs_sigstack) return;
    memset(&ss, 0, sizeof(ss));
    ss.ss_flags = SS_DISABLE;
    ss.ss_size = gs_sigstack_size();
    sigaltstack(&ss, NULL);
    free(gs_sigstack);
    gs_sigstack = NULL;
}

static uint8_t *gs_reserve_region(void) {
    if (gs_nregions == GS_MAX_STACKS * 4)
        gs_panic("too many data stack regions");
    /* Commit-on-touch via overcommit; the gap at the end stays PROT_NONE. */
    void *p = mmap(NULL, GS_REGION_SIZE, PROT_READ | PROT_WRITE,
                   MAP_PRIVATE | MAP_ANONYMOUS
                   #ifdef MAP_NORESERVE
                       | MAP_NORESERVE
                   #endif
                   , -1, 0);
    if (p == MAP_FAILED) gs_panic("cannot reserve data stack address space");
    if (mprotect((uint8_t *)p + GS_STACK_RESERVE, GS_STACK_GAP, PROT_NONE)) {
        munmap(p, GS_REGION_SIZE);
        gs_panic("cannot protect data stack guard gap");
    }
    long i = gs_nregions;
    gs_regions[i] = (uint8_t *)p;
    gs_nregions = i + 1;
    return (uint8_t *)p;
}

static void gs_release_region(uint8_t *base) {
    if (munmap(base, GS_REGION_SIZE)) gs_panic("cannot release data stack address space");
}

#endif

/* The current thread program's stack block. gs_sp-relative indices resolve
   through this; stacks materialize lazily as call depth first reaches them. */
static GS_TLS gs_stack *gs_stks;
static GS_TLS int64_t gs_nstks;

/* The current program instance's globals (goose_spec.md 11.1), a struct the
   compiler lays out: main's is its one static instance, a worker's a fresh
   copy of the globals its program uses, taken from the spawning instance
   at spawn like the arguments (11.2). No global is shared between program
   instances; the only C statics a program shares are read-only ones. */
static GS_TLS void *gs_gl;

#define GS(i) (&gs_stks[i])

/* A function's prologue asks for the stacks it uses, naming its declaration
   (gs_init_globals names an initializer) for the abort when there are not
   enough. */
static void gs_stks_grow(int64_t n, const char *file, int line) {
    if (n > GS_MAX_STACKS) gs_abort(GS_E_STACKS, file, line);
    while (gs_nstks < n) {
        gs_stack *s = &gs_stks[gs_nstks++];
        s->top = gs_reserve_region();
)GSRT"
R"GSRT(    }
}

#define GS_ENSURE(n, f, l) do { if ((n) > gs_nstks) gs_stks_grow((n), (f), (l)); } while (0)

static gs_stack *gs_new_stack_block(void) {
    gs_stack *b = (gs_stack *)calloc(GS_MAX_STACKS, sizeof(gs_stack));
    if (!b) gs_panic("out of memory allocating stack block");
    return b;
}

static void gs_stack_init(gs_stack *s) {
    s->top = gs_reserve_region();
}

/* Workers own all their registered regions (globals belong to main). No
   Goose reference to these mappings may outlive the worker. Unregister
   before unmapping, then discard the now-useless bump pointers. The
   thread's alternate signal stack goes with them. */
static void gs_free_thread_stacks(void) {
    while (gs_nregions) {
        long i = gs_nregions - 1;
        uint8_t *base = gs_regions[i];
        gs_nregions = i;
        gs_regions[i] = NULL;
        gs_release_region(base);
    }
    free(gs_stks);
    gs_stks = NULL;
    gs_nstks = 0;
    gs_native_stack_free();
}

static void gs_rt_init(void) {
    // Unbuffered stdout: output is never lost to an abort or a killed run,
    // and interleaves correctly with stderr diagnostics. Revisit if print
    // throughput ever matters.
    setvbuf(stdout, NULL, _IONBF, 0);
    gs_regions_init();
    gs_native_stack_init();
    gs_stks = gs_new_stack_block();
    gs_nstks = 0;
}

/* ---------------------------------------------------------------------------
   Slice pools (§5.4, `reusable[]`). The freelist is a run of (index, count)
   spans on a data stack of its own, sorted by index, no two of them
   touching. The emitted code grows the element region and fills elements;
   these only keep the spans, and each takes the run's base, its span count
   and its stack's top, which stays at the end of the run. Indices and counts
   are in elements. Every span comes from a slice of the pool, so spans stay
   inside the pool's length whatever the program frees: freeing a slice twice
   leaves overlapping spans that hand the same elements out twice, never
   anything outside the pool. */

typedef struct { int64_t idx, cnt; } gs_span;

/* The number of spans starting at or before idx. */
static int64_t gs_spans_upto(const gs_span *s, int64_t n, int64_t idx) {
    int64_t lo = 0, hi = n;
    while (lo < hi) {
        int64_t mid = lo + (hi - lo) / 2;
        if (s[mid].idx <= idx) lo = mid + 1;
        else hi = mid;
    }
    return lo;
}

static void gs_spans_drop(gs_span *s, int64_t *n, uint8_t **top, int64_t at) {
    memmove(s + at, s + at + 1, (size_t)(*n - at - 1) * sizeof(gs_span));
    (*n)--;
    *top -= sizeof(gs_span);
}

/* Takes cnt elements off the front of span `at`, or all of a span that
   holds no more. */
static void gs_spans_take(gs_span *s, int64_t *n, uint8_t **top, int64_t at, int64_t cnt) {
    if (s[at].cnt <= cnt) {
        gs_spans_drop(s, n, top, at);
        return;
    }
    s[at].idx += cnt;
    s[at].cnt -= cnt;
}

/* Where a run of cnt elements goes in a pool of len elements, for
   alloc_slice and for a slice realloc_slice moves: the front of the first
   span holding it, else the end of the array, where a free span that reaches
   the end starts the run. The caller grows the array to the returned index
   plus cnt. First fit rather than best: in index order it packs runs toward
   the start and leaves the end free, and it stops scanning at the fit. */
static int64_t gs_spans_alloc(uint8_t *base, int64_t *n, uint8_t **top, int64_t len,
                              int64_t cnt) {
    gs_span *s = (gs_span *)base;
    int64_t at = 0, idx;
    if (cnt == 0) return len;
    while (at < *n && s[at].cnt < cnt) at++;
    if (at == *n) {
        if (*n == 0 || s[*n - 1].idx + s[*n - 1].cnt != len) return len;
        at = *n - 1;
    }
    idx = s[at].idx;
    gs_spans_take(s, n, top, at, cnt);
    return idx;
}

/* realloc_slice growing a slice in place: whether cnt more elements can
   follow it where it ends, at `end` -- taken from a free span that starts
   there, or from past the end of the pool, directly or through such a span
   reaching it. The caller grows the array to whatever lies past its end. */
static int gs_spans_grow(uint8_t *base, int64_t *n, uint8_t **top, int64_t len, int64_t end,
                         int64_t cnt) {
    gs_span *s = (gs_span *)base;
    int64_t at;
    if (end == len) return 1;
    at = gs_spans_upto(s, *n, end) - 1;
    if (at < 0 || s[at].idx != end) return 0;
    if (s[at].cnt < cnt && end + s[at].cnt != len) return 0;
    gs_spans_take(s, n, top, at, cnt);
    return 1;
}

/* free_slice, and what realloc_slice lets go of: [idx, idx + cnt) back on
   the freelist, merged with the spans it touches. */
static void gs_spans_free(uint8_t *base, int64_t *n, uint8_t **top, int64_t idx, int64_t cnt) {
    gs_span *s = (gs_span *)base;
    int64_t at;
    int prev, next;
    if (cnt <= 0) return;
    at = gs_spans_upto(s, *n, idx);
    prev = at > 0 && s[at - 1].idx + s[at - 1].cnt == idx;
    next = at < *n && idx + cnt == s[at].idx;
    if (prev) {
        s[at - 1].cnt += cnt;
        if (next) {
            s[at - 1].cnt += s[at].cnt;
            gs_spans_drop(s, n, top, at);
        }
    } else if (next) {
        s[at].idx = idx;
        s[at].cnt += cnt;
    } else {
        memmove(s + at + 1, s + at, (size_t)(*n - at) * sizeof(gs_span));
        s[at].idx = idx;
        s[at].cnt = cnt;
        (*n)++;
        *top += sizeof(gs_span);
    }
}

/* ---------------------------------------------------------------------------
   varint (§3.6): ULEB128; struct/payload/offset values additionally zigzag. */

static int64_t gs_uleb_read(const uint8_t *p) {
    uint64_t v = 0;
    int shift = 0;
    for (;;) {
        uint8_t b = *p++;
        v |= (uint64_t)(b & 0x7f) << shift;
        if (!(b & 0x80)) return (int64_t)v;
        shift += 7;
    }
}

static int64_t gs_uleb_size(const uint8_t *p) {
    const uint8_t *q = p;
    while (*q & 0x80) q++;
    return (int64_t)(q - p) + 1;
}

/* An inline array's length prefix is one byte unless the array holds 128
   elements or more, so the two macros below are what the compiler emits for
   it: a load, a test, and the byte. The continuation is a call the caller's
   loop does not contain, and reaching it means there is a large array to
   walk, against which the call costs nothing. Both read the pointer twice,
   which the emitting sites already assume (they form the element address
   from the same text). A varint *value*, by contrast, is whatever the
   program stored, so scalar fields and relative offsets keep the loop above
   inline, where the compilers peel the first byte themselves. */

static GS_NOINLINE int64_t gs_uleb_read_slow(const uint8_t *p) {
    return gs_uleb_read(p);
}

static GS_NOINLINE int64_t gs_uleb_size_slow(const uint8_t *p) {
    return gs_uleb_size(p);
}

#define GS_ULEB_READ(p) ((*(p) & 0x80) ? gs_uleb_read_slow(p) : (int64_t)*(p))
#define GS_ULEB_SIZE(p) ((*(p) & 0x80) ? gs_uleb_size_slow(p) : (int64_t)1)

static int64_t gs_uleb_write(uint8_t *p, uint64_t v) {
    uint8_t *q = p;
    for (;;) {
        uint8_t b = v & 0x7f;
        v >>= 7;
        if (v) *q++ = b | 0x80; else { *q++ = b; break; }
    }
    return (int64_t)(q - p);
}

static int64_t gs_zig_read(const uint8_t *p) {
    uint64_t u = (uint64_t)gs_uleb_read(p);
    return (int64_t)((u >> 1) ^ (0u - (u & 1)));
}

static int64_t gs_zig_write(uint8_t *p, int64_t v) {
    return gs_uleb_write(p, ((uint64_t)v << 1) ^ (uint64_t)(v >> 63));
}

/* ---------------------------------------------------------------------------
   Verified loading (docs/design/serialization.md): what the generated
   gs_verify_<T> walkers are built from. The bytes are untrusted until the
   walk finishes, so every read here is bounded by the image end and reports
   a malformed encoding instead of running past it. */

/* The ULEB128 at p, or 0 if it runs past `end`, past ten bytes, or carries
)GSRT"
R"GSRT(   payload bits above the 64th, or is not shortest. The result is the byte count. */
static int64_t gs_uleb_check(const uint8_t *p, const uint8_t *end, uint64_t *out) {
    uint64_t v = 0;
    int shift = 0;
    const uint8_t *q = p;
    for (;;) {
        uint8_t b;
        if (q >= end) return 0;
        b = *q++;
        if (shift > 63 || (shift == 63 && (b & 0x7e))) return 0;
        v |= (uint64_t)(b & 0x7f) << shift;
        if (!(b & 0x80)) {
            if (shift && !b) return 0;  /* Redundant high zero group. */
            break;
        }
        shift += 7;
    }
    *out = v;
    return (int64_t)(q - p);
}

/* The same for a signed (zigzag) varint: a value field or a self-relative
   offset of varint width (3.6). */
static int64_t gs_zig_check(const uint8_t *p, const uint8_t *end, int64_t *out) {
    uint64_t u = 0;
    int64_t k = gs_uleb_check(p, end, &u);
    if (k) *out = (int64_t)((u >> 1) ^ (0u - (u & 1)));
    return k;
}

/* Element starts, one bit per image byte: the framing pass sets them and the
   link pass asks whether an offset is one. Only images of variable-size
   elements need it -- for fixed ones a start is a multiple of the size. The
   bitmap is one data stack's worth of scratch, so the largest image that can
   be verified is eight times a stack's reservation; from_bytes rejects a
   larger one rather than growing into the guard region. */
#define GS_BM_SET(bm, i) ((bm)[(uint64_t)(i) >> 3] |= (uint8_t)(1u << ((i) & 7)))
#define GS_BM_GET(bm, i) (((bm)[(uint64_t)(i) >> 3] >> ((i) & 7)) & 1)
#define GS_BM_MAX ((int64_t)(GS_STACK_RESERVE))

/* An image is little-endian by definition (serialization.md 7), which every
   target this compiles for is. The test is a constant to any optimizer; it is
   here so that a big-endian host fails loudly instead of writing bytes that
   only it can read back. */
static int gs_is_le(void) {
    const uint16_t one = 1;
    return *(const uint8_t *)&one == 1;
}

/* ---------------------------------------------------------------------------
   Text forms (§3.7): the gs_fmt_* functions write a value's text at dst and
   return the byte count (at most GS_FMT_MAX); print/str/format are built on
   them. A float takes the shortest form that still round-trips. */

#define GS_FMT_MAX 32

static int64_t gs_fmt_i64(uint8_t *dst, int64_t v) {
    return (int64_t)snprintf((char *)dst, GS_FMT_MAX, "%lld", (long long)v);
}

static int64_t gs_fmt_u64(uint8_t *dst, uint64_t v) {
    return (int64_t)snprintf((char *)dst, GS_FMT_MAX, "%llu", (unsigned long long)v);
}

/* C99 asks for at least two exponent digits; the older Microsoft C runtime
   (which is what tcc links against on Windows) always writes three. Trim the
   padding, so a float's text form is the language's and not the backend's. */
static int gs_fmt_exp(char *s, int n) {
    char *e = (char *)memchr(s, 'e', (size_t)n);
    if (!e) return n;
    char *d = e + 2;                    /* past the 'e' and the exponent sign */
    char *p = d;
    int digits = n - (int)(d - s);
    while (digits > 2 && *p == '0') p++, digits--;
    if (p != d) {
        memmove(d, p, (size_t)digits);
        n = (int)(d - s) + digits;
        s[n] = 0;
    }
    return n;
}

static int64_t gs_fmt_f64(uint8_t *dst, double v) {
    int n = snprintf((char *)dst, GS_FMT_MAX, "%.15g", v);
    if (strtod((char *)dst, NULL) != v) n = snprintf((char *)dst, GS_FMT_MAX, "%.17g", v);
    return gs_fmt_exp((char *)dst, n);
}

static int64_t gs_fmt_bool(uint8_t *dst, int64_t v) {
    memcpy(dst, v ? "true" : "false", v ? 4 : 5);
    return v ? 4 : 5;
}

/* A u8 array inside an aggregate: quoted, with the escapes Goose reads. */
static int64_t gs_fmt_quoted(uint8_t *dst, const uint8_t *s, int64_t n) {
    uint8_t *d = dst;
    *d++ = '"';
    for (int64_t i = 0; i < n; i++) {
        uint8_t c = s[i];
        switch (c) {
            case '"': *d++ = '\\'; *d++ = '"'; break;
            case '\\': *d++ = '\\'; *d++ = '\\'; break;
            case '\n': *d++ = '\\'; *d++ = 'n'; break;
            case '\r': *d++ = '\\'; *d++ = 'r'; break;
            case '\t': *d++ = '\\'; *d++ = 't'; break;
            default: *d++ = c; break;
        }
    }
    *d++ = '"';
    return (int64_t)(d - dst);
}

/* print(...) (§3.7): each argument's text, then a newline. stdout is
   unbuffered (gs_rt_init), so every piece is its own write; revisit if print
   throughput ever matters. */

static void gs_out_int(int64_t v) { printf("%lld", (long long)v); }
static void gs_out_uint(uint64_t v) { printf("%llu", (unsigned long long)v); }
static void gs_out_flt(double v) {
    uint8_t buf[GS_FMT_MAX];
    fwrite(buf, 1, (size_t)gs_fmt_f64(buf, v), stdout);
}
static void gs_out_bool(int64_t v) { fputs(v ? "true" : "false", stdout); }
static void gs_out_bytes(const uint8_t *p, int64_t len) { fwrite(p, 1, (size_t)len, stdout); }
static void gs_out_nl(void) { fputc('\n', stdout); }
)GSRT"
    ) },
    { "runtime_threads.h", string_view(
R"GSRT(/* Goose runtime — threads and typed queues (§11.2). Prepended after
   runtime.h; everything is compiled out unless the program uses threads or
   queues (the compiler defines GS_NEED_THREADS 1 before the runtime paste).
   This is the one part of the runtime allowed to allocate internally. */

/* hardware_threads() sizes worker pools, and a program that spawns none may
   still ask; it needs nothing below. */
#ifdef _WIN32
static int64_t gs_hardware_threads(void) {
    SYSTEM_INFO si;
    GetSystemInfo(&si);
    return (int64_t)si.dwNumberOfProcessors;
}
#else
#include <unistd.h>
static int64_t gs_hardware_threads(void) {
    long n = sysconf(_SC_NPROCESSORS_ONLN);
    return n > 0 ? (int64_t)n : 1;
}
#endif

#if GS_NEED_THREADS

#ifdef _WIN32

typedef SRWLOCK gs_mutex;
typedef CONDITION_VARIABLE gs_cond;
#define GS_MUTEX_INIT SRWLOCK_INIT
#define GS_COND_INIT  CONDITION_VARIABLE_INIT
#define gs_mutex_lock(m)   AcquireSRWLockExclusive(m)
#define gs_mutex_unlock(m) ReleaseSRWLockExclusive(m)
#define gs_cond_wait(c, m) SleepConditionVariableSRW((c), (m), INFINITE, 0)
#define gs_cond_signal(c)  WakeConditionVariable(c)
#define gs_cond_broadcast(c) WakeAllConditionVariable(c)

#else  /* posix */

#include <pthread.h>

typedef pthread_mutex_t gs_mutex;
typedef pthread_cond_t gs_cond;
#define GS_MUTEX_INIT PTHREAD_MUTEX_INITIALIZER
#define GS_COND_INIT  PTHREAD_COND_INITIALIZER
#define gs_mutex_lock(m)   pthread_mutex_lock(m)
#define gs_mutex_unlock(m) pthread_mutex_unlock(m)
#define gs_cond_wait(c, m) pthread_cond_wait((c), (m))
#define gs_cond_signal(c)  pthread_cond_signal(c)
#define gs_cond_broadcast(c) pthread_cond_broadcast(c)

#endif

/* ---------------------------------------------------------------------------
   Workers. Each runs its thread program on a fresh stack block; flat argument
   values are packed by the caller into one contiguous buffer and unpacked by
   a compiler-generated entry thunk. Only active workers have records. IDs
   increase monotonically, so an issued ID absent from the active list has
   completed; neither repeated waits nor unjoined workers retain resources.
   Workers still running at process exit are killed by teardown (§11.2). */

typedef struct gs_thread {
    struct gs_thread *next;
    int64_t id;
    void (*entry)(uint8_t *args);
    uint8_t *args;
} gs_thread;

static gs_thread *gs_threads;
static int64_t gs_numthreads;
static gs_mutex gs_threads_mutex = GS_MUTEX_INIT;
static gs_cond gs_threads_done = GS_COND_INIT;
static GS_TLS int64_t gs_current_thread_id = -1;

#ifdef _WIN32
static DWORD WINAPI gs_thread_main(LPVOID p)
#else
static void *gs_thread_main(void *p)
#endif
{
    gs_thread *t = (gs_thread *)p;
    gs_native_stack_init();
    gs_current_thread_id = t->id;
    gs_stks = gs_new_stack_block();
    gs_nstks = 0;
    t->entry(t->args);
    free(t->args);
    gs_free_thread_stacks();

    /* Publish completion only after all Goose storage has been released.
       No waiter retains a pointer to this record. The detached native thread
       releases its own final OS stack/TLS state on returning below. */
    gs_mutex_lock(&gs_threads_mutex);
    gs_thread **slot = &gs_threads;
    while (*slot != t) slot = &(*slot)->next;
    *slot = t->next;
    free(t);
    gs_cond_broadcast(&gs_threads_done);
    gs_mutex_unlock(&gs_threads_mutex);
    #ifdef _WIN32
        return 0;
    #else
        return NULL;
    #endif
}

static int64_t gs_thread_spawn(void (*entry)(uint8_t *), const void *args, int64_t argsize) {
    if (argsize < 0 || (uint64_t)argsize > SIZE_MAX)
        gs_panic("invalid thread argument size");
    gs_thread *t = (gs_thread *)malloc(sizeof(gs_thread));
    if (!t) gs_panic("out of memory spawning thread");
    t->entry = entry;
    t->args = (uint8_t *)malloc(argsize ? (size_t)argsize : 1);
    if (!t->args) {
        free(t);
        gs_panic("out of memory spawning thread");
    }
    if (argsize) memcpy(t->args, args, (size_t)argsize);
    gs_mutex_lock(&gs_threads_mutex);
    if (gs_numthreads == INT64_MAX) gs_panic("thread id space exhausted");
    int64_t id = gs_numthreads++;
    t->id = id;
    t->next = gs_threads;
    gs_threads = t;
    int failed;
    #ifdef _WIN32
        HANDLE handle = CreateThread(NULL, 0, gs_thread_main, t, 0, NULL);
        failed = handle == NULL;
        /* Closing the handle does not stop the worker. Completion is tracked
           above, so callers never need to retain or join a native handle. */
        if (handle && !CloseHandle(handle)) gs_panic("cannot close thread handle");
    #else
        pthread_t handle;
        pthread_attr_t attr;
        failed = pthread_attr_init(&attr);
        if (!failed) {
            failed = pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
            if (!failed) failed = pthread_create(&handle, &attr, gs_thread_main, t);
            pthread_attr_destroy(&attr);
        }
    #endif
    if (failed) {
        gs_threads = t->next;
        --gs_numthreads;
        gs_mutex_unlock(&gs_threads_mutex);
        free(t->args);
        free(t);
        gs_panic("cannot create thread");
    }
    gs_mutex_unlock(&gs_threads_mutex);
    return id;
}

static void gs_thread_wait(int64_t id, const char *file, int line) {
    gs_mutex_lock(&gs_threads_mutex);
    if (id < 0 || id >= gs_numthreads) gs_abort(GS_E_THREADID, file, line);
    if (id == gs_current_thread_id) gs_abort(GS_E_THREADSELF, file, line);
    for (;;) {
        gs_thread *t = gs_threads;
        while (t && t->id != id) t = t->next;
        if (!t) break;
        gs_cond_wait(&gs_threads_done, &gs_threads_mutex);
    }
    gs_mutex_unlock(&gs_threads_mutex);
}

/* ---------------------------------------------------------------------------
   Typed queues: one per flat element type used by the program (the compiler
   emits a gs_queue global per type). Values are contiguous byte images. */

typedef struct gs_qnode {
    struct gs_qnode *next;
    int64_t size;
    /* Value bytes follow the header. */
} gs_qnode;

typedef struct {
    gs_qnode *head, *tail;
    gs_mutex mutex;
    gs_cond cond;
} gs_queue;

#define GS_QUEUE_INIT { NULL, NULL, GS_MUTEX_INIT, GS_COND_INIT }

static void gs_qput(gs_queue *q, const void *data, int64_t size) {
    gs_qnode *n = (gs_qnode *)malloc(sizeof(gs_qnode) + (size_t)size);
    if (!n) gs_panic("out of memory in qput");
    n->next = NULL;
    n->size = size;
    memcpy(n + 1, data, (size_t)size);
    gs_mutex_lock(&q->mutex);
    if (q->tail) q->tail->next = n; else q->head = n;
    q->tail = n;
    gs_mutex_unlock(&q->mutex);
    gs_cond_signal(&q->cond);
}

/* Both return a malloc'd node the caller copies from and frees; qpoll returns
   NULL when the queue is empty. */
static gs_qnode *gs_qget(gs_queue *q) {
    gs_mutex_lock(&q->mutex);
    while (!q->head) gs_cond_wait(&q->cond, &q->mutex);
    gs_qnode *n = q->head;
    q->head = n->next;
    if (!q->head) q->tail = NULL;
    gs_mutex_unlock(&q->mutex);
    return n;
}

static gs_qnode *gs_qpoll(gs_queue *q) {
    gs_mutex_lock(&q->mutex);
    gs_qnode *n = q->head;
    if (n) {
        q->head = n->next;
        if (!q->head) q->tail = NULL;
    }
    gs_mutex_unlock(&q->mutex);
    return n;
}

#endif  /* GS_NEED_THREADS */
)GSRT"
    ) },
    { "runtime_os.h", string_view(
R"GSRT(/* Goose runtime: extern-fn support and the OS primitives behind
   stdlib/os.goose (spec §7.10). Unlike the other runtime files this one is
   spliced in after the generated type declarations, since its functions
   are written against them: sl_u8 (a u8 slice: data, len) and gs_rref (a
   reference to a resizable: its header and its data stack). The generated
   program calls these directly from `extern "gs_os_..." fn` declarations;
   no prototype is emitted for a symbol defined here. */

#include <time.h>
#ifndef _WIN32
#include <errno.h>
#include <fcntl.h>
#include <dirent.h>
#include <sys/stat.h>
#endif

/* Appends n bytes to the u8[>..] a builder reference points at: the
   resizable's elements top its stack, so the bytes go at the stack top and
   the header's count grows. */
static void gs_bld_append(gs_rref b, const void *p, int64_t n) {
    if (n <= 0) return;
    memcpy(b.stk->top, p, (size_t)n);
    b.stk->top += n;
    b.hdr->len += n;
}

/* Paths are UTF-8 on every platform, and reach the C APIs NUL-terminated in
   a buffer of GS_OS_PATH_MAX characters. A path that would not fit, that
   holds a NUL byte (where C would end it) or, on Windows, that is not UTF-8
   is refused: cut short or read another way, it could name another file. */
#define GS_OS_PATH_MAX 4096

#ifdef _WIN32
/* Windows names files in UTF-16, which its wide APIs take as it is; the
   narrow ones read their bytes in the ANSI code page. */
typedef wchar_t gs_os_char;
#define gs_os_fopen(p, mode) _wfopen(p, L##mode)
/* Vista's; TinyCC's winnls.h predates it. */
#ifndef WC_ERR_INVALID_CHARS
#define WC_ERR_INVALID_CHARS 0x80
#endif
#else
typedef char gs_os_char;
#define gs_os_fopen(p, mode) fopen(p, mode)
#endif

/* The native form of a path, or of an environment variable's name, in buf
   (GS_OS_PATH_MAX characters): its length, or -1 where it is refused. */
static int gs_os_native(sl_u8 s, gs_os_char *buf) {
    if (s.len >= GS_OS_PATH_MAX || (s.len > 0 && memchr(s.data, 0, (size_t)s.len)))
        return -1;
    int n = (int)s.len;
#ifdef _WIN32
    /* A UTF-16 path has no more units than its UTF-8 form has bytes. */
    if (n > 0) {
        n = MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, (const char *)s.data, n, buf,
                                GS_OS_PATH_MAX - 1);
        if (n == 0) return -1;
    }
#else
    gs_memcpy(buf, s.data, (size_t)n);
#endif
    buf[n] = 0;
    return n;
}

#ifdef _WIN32
/* Appends n UTF-16 units as UTF-8; where they are not valid UTF-16, appends
   nothing and returns 0. */
static int gs_os_append_wide(gs_rref out, const wchar_t *w, int n) {
    if (n <= 0) return 1;
    int k = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, w, n, NULL, 0, NULL, NULL);
    char *s = k > 0 ? (char *)malloc((size_t)k) : NULL;
    int ok = s && WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, w, n, s, k, NULL, NULL) == k;
    if (ok) gs_bld_append(out, s, k);
    free(s);
    return ok;
}
#else
/* An fsync that reaches the disk: on macOS a plain one stops at the drive's
   cache. */
static int gs_os_fsync(int fd) {
    #ifdef F_FULLFSYNC
        if (fcntl(fd, F_FULLFSYNC) == 0) return 1;
    #endif
    return fsync(fd) == 0;
}

/* A rename is on the disk once the directory holding the new name is (what
   MOVEFILE_WRITE_THROUGH waits for on Windows). Best effort: the rename has
   happened either way. */
static void gs_os_sync_dir(const char *path) {
    char dir[GS_OS_PATH_MAX];
    const char *slash = strrchr(path, '/');
    size_t n = slash ? (size_t)(slash - path) : 0;
    if (slash && n == 0) n = 1;
    if (n) memcpy(dir, path, n);
    else dir[n++] = '.';
    dir[n] = 0;
    int fd = open(dir, O_RDONLY);
    if (fd < 0) return;
    gs_os_fsync(fd);
    close(fd);
}
#endif

/* What a native path names: 0 nothing that can be reached, 1 something
   other than a directory, 2 a directory. */
static int gs_os_kind(const gs_os_char *p) {
#ifdef _WIN32
    DWORD a = GetFileAttributesW(p);
    if (a == INVALID_FILE_ATTRIBUTES) return 0;
    return (a & FILE_ATTRIBUTE_DIRECTORY) ? 2 : 1;
#else
    struct stat st;
    if (stat(p, &st) != 0) return 0;
    return S_ISDIR(st.st_mode) ? 2 : 1;
#endif
}

static uint8_t gs_os_read_file(sl_u8 path, gs_rref out) {
    gs_os_char p[GS_OS_PATH_MAX];
    if (gs_os_native(path, p) < 0) return 0;
    FILE *f = gs_os_fopen(p, "rb");
    if (!f) return 0;
    uint8_t buf[65536];
    for (;;) {
        size_t n = fread(buf, 1, sizeof buf, f);
        if (n == 0) break;
        gs_bld_append(out, buf, (int64_t)n);
    }
    int bad = ferror(f);
    fclose(f);
    return bad ? 0 : 1;
}

/* write_file and append_file. */
static uint8_t gs_os_put_file(sl_u8 path, sl_u8 data, int append) {
    gs_os_char p[GS_OS_PATH_MAX];
    if (gs_os_native(path, p) < 0) return 0;
    FILE *f = append ? gs_os_fopen(p, "ab") : gs_os_fopen(p, "wb");
    if (!f) return 0;
    size_t n = (size_t)(data.len < 0 ? 0 : data.len);
    int ok = fwrite(data.data, 1, n, f) == n;
    if (fclose(f) != 0) ok = 0;
    return ok ? 1 : 0;
}

static uint8_t gs_os_write_file(sl_u8 path, sl_u8 data) { return gs_os_put_file(path, data, 0); }

static uint8_t gs_os_append_file(sl_u8 path, sl_u8 data) { return gs_os_put_file(path, data, 1); }

static uint8_t gs_os_file_exists(sl_u8 path) {
    gs_os_char p[GS_OS_PATH_MAX];
    return gs_os_native(path, p) >= 0 && gs_os_kind(p) == 1;
}

static uint8_t gs_os_remove_file(sl_u8 path) {
    gs_os_char p[GS_OS_PATH_MAX];
    if (gs_os_native(path, p) < 0) return 0;
#ifdef _WIN32
    return DeleteFileW(p) != 0;
#else
    /* Not remove, which takes an empty directory as well. */
    return unlink(p) == 0;
#endif
}

/* Replaces `to` if it exists, in one step: `to` names the old file or the
   moved one, never neither. */
static uint8_t gs_os_rename_file(sl_u8 from, sl_u8 to) {
    gs_os_char f[GS_OS_PATH_MAX], t[GS_OS_PATH_MAX];
    if (gs_os_native(from, f) < 0 || gs_os_native(to, t) < 0) return 0;
#ifdef _WIN32
    return MoveFileExW(f, t, MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH) != 0;
#else
    if (rename(f, t) != 0) return 0;
    gs_os_sync_dir(t);
    return 1;
#endif
}

static uint64_t gs_os_random_u64(void);

/* Writes data to a new file beside path, flushes it to the disk and renames
   it over path, so that path holds either its old contents or all of the
   new ones whatever happens meanwhile; on a failure the new file is removed.
   Its name is path's with a random tag and ".tmp" added, created only if
   nothing has that name already: one that does belongs to someone else, and
   another tag is drawn. */
static uint8_t gs_os_write_file_atomic(sl_u8 path, sl_u8 data) {
    gs_os_char p[GS_OS_PATH_MAX], t[GS_OS_PATH_MAX + 21];
    int n = gs_os_native(path, p);
    if (n <= 0) return 0;
    const uint8_t *d = data.data;
    int64_t left = data.len;
    for (int tries = 0; tries < 8; tries++) {
        uint64_t tag = gs_os_random_u64();
        int k = n;
        memcpy(t, p, (size_t)n * sizeof *t);
        t[k++] = '.';
        for (int s = 60; s >= 0; s -= 4) t[k++] = "0123456789abcdef"[(tag >> s) & 15];
        t[k++] = '.';
        t[k++] = 't';
        t[k++] = 'm';
        t[k++] = 'p';
        t[k] = 0;
        int ok = 1;
#ifdef _WIN32
        HANDLE h = CreateFileW(t, GENERIC_WRITE, 0, NULL, CREATE_NEW, FILE_ATTRIBUTE_NORMAL, NULL);
        if (h == INVALID_HANDLE_VALUE) {
            if (GetLastError() == ERROR_FILE_EXISTS) continue;
            return 0;
        }
        while (ok && left > 0) {
            DWORD chunk = left > (1 << 30) ? (DWORD)1 << 30 : (DWORD)left, wrote = 0;
            ok = WriteFile(h, d, chunk, &wrote, NULL) && wrote == chunk;
            d += chunk;
            left -= chunk;
        }
        ok = ok && FlushFileBuffers(h);
        if (!CloseHandle(h)) ok = 0;
        ok = ok && MoveFileExW(t, p, MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH);
        if (!ok) DeleteFileW(t);
#else
        int fd = open(t, O_WRONLY | O_CREAT | O_EXCL, 0666);
)GSRT"
R"GSRT(        if (fd < 0) {
            if (errno == EEXIST) continue;
            return 0;
        }
        while (ok && left > 0) {
            ssize_t w = write(fd, d, left > (1 << 30) ? (size_t)1 << 30 : (size_t)left);
            if (w < 0 && errno == EINTR) continue;
            ok = w > 0;
            if (ok) {
                d += w;
                left -= w;
            }
        }
        ok = ok && gs_os_fsync(fd);
        if (close(fd) != 0) ok = 0;
        ok = ok && rename(t, p) == 0;
        if (ok) gs_os_sync_dir(p);
        else unlink(t);
#endif
        return ok ? 1 : 0;
    }
    return 0;
}

/* True where path is a directory afterwards, one that was there already
   included. */
static uint8_t gs_os_make_dir(sl_u8 path) {
    gs_os_char p[GS_OS_PATH_MAX];
    if (gs_os_native(path, p) < 0) return 0;
#ifdef _WIN32
    if (CreateDirectoryW(p, NULL)) return 1;
#else
    if (mkdir(p, 0777) == 0) return 1;
#endif
    return gs_os_kind(p) == 2;
}

static uint8_t gs_os_is_dir(sl_u8 path) {
    gs_os_char p[GS_OS_PATH_MAX];
    return gs_os_native(path, p) >= 0 && gs_os_kind(p) == 2;
}

/* An empty directory. */
static uint8_t gs_os_remove_dir(sl_u8 path) {
    gs_os_char p[GS_OS_PATH_MAX];
    if (gs_os_native(path, p) < 0) return 0;
#ifdef _WIN32
    return RemoveDirectoryW(p) != 0;
#else
    return rmdir(p) == 0;
#endif
}

/* The names a listing collects before sorting them: NUL-terminated, one
   after another. */
typedef struct {
    char *text;
    size_t len, cap, count;
} gs_os_names;

/* A name with a newline in it cannot be a line of the listing, and is left
   out. */
static int gs_os_names_add(gs_os_names *ns, const char *name, size_t n) {
    if (memchr(name, '\n', n)) return 1;
    if (ns->len + n + 1 > ns->cap) {
        size_t cap = ns->cap ? ns->cap * 2 : 4096;
        while (cap < ns->len + n + 1) cap *= 2;
        char *text = (char *)realloc(ns->text, cap);
        if (!text) return 0;
        ns->text = text;
        ns->cap = cap;
    }
    memcpy(ns->text + ns->len, name, n);
    ns->text[ns->len + n] = 0;
    ns->len += n + 1;
    ns->count++;
    return 1;
}

static int gs_os_name_order(const void *a, const void *b) {
    return strcmp(*(const char *const *)a, *(const char *const *)b);
}

/* Appends the names in bytewise order, each followed by a newline. */
static int gs_os_names_put(gs_os_names *ns, gs_rref out) {
    if (!ns->count) return 1;
    const char **v = (const char **)malloc(ns->count * sizeof *v);
    if (!v) return 0;
    size_t i = 0;
    for (size_t at = 0; at < ns->len; at += strlen(ns->text + at) + 1) v[i++] = ns->text + at;
    qsort(v, ns->count, sizeof *v, gs_os_name_order);
    for (i = 0; i < ns->count; i++) {
        gs_bld_append(out, v[i], (int64_t)strlen(v[i]));
        gs_bld_append(out, "\n", 1);
    }
    free(v);
    return 1;
}

/* Appends the name of every entry of a directory but "." and "..", sorted
   so that a listing does not depend on the file system; on a failure
   appends nothing. */
static uint8_t gs_os_list_dir(sl_u8 path, gs_rref out) {
    gs_os_char p[GS_OS_PATH_MAX + 2];
    int n = gs_os_native(path, p);
    if (n <= 0) return 0;
    gs_os_names ns = { 0 };
    int ok = 1;
#ifdef _WIN32
    /* FindFirstFileW takes a pattern, which "*" after the directory makes
       every entry. */
    int dirlen = n;
    if (p[n - 1] != '/' && p[n - 1] != '\\' && p[n - 1] != ':') p[n++] = '\\';
    p[n++] = '*';
    p[n] = 0;
    WIN32_FIND_DATAW e;
    HANDLE h = FindFirstFileW(p, &e);
    if (h == INVALID_HANDLE_VALUE) {
        /* No entry at all, not even "." and "..": the empty root of a drive. */
        int empty = GetLastError() == ERROR_FILE_NOT_FOUND;
        p[dirlen] = 0;
        return empty && gs_os_kind(p) == 2;
    }
    do {
        const wchar_t *w = e.cFileName;
        if (w[0] == '.' && (!w[1] || (w[1] == '.' && !w[2]))) continue;
        /* A name that is not valid UTF-16 has no UTF-8 spelling, and is left
           out. */
        char name[1024];
        int k = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, w, -1, name, sizeof name,
                                    NULL, NULL);
        if (k > 1 && !gs_os_names_add(&ns, name, (size_t)k - 1)) ok = 0;
    } while (ok && FindNextFileW(h, &e));
    if (ok && GetLastError() != ERROR_NO_MORE_FILES) ok = 0;
    FindClose(h);
#else
    DIR *d = opendir(p);
    if (!d) return 0;
    for (;;) {
        errno = 0;
        struct dirent *e = readdir(d);
        if (!e) {
            ok = errno == 0;
            break;
        }
        const char *w = e->d_name;
        if (w[0] == '.' && (!w[1] || (w[1] == '.' && !w[2]))) continue;
        if (!gs_os_names_add(&ns, w, strlen(w))) {
            ok = 0;
            break;
        }
    }
    closedir(d);
#endif
    ok = ok && gs_os_names_put(&ns, out);
    free(ns.text);
    return ok ? 1 : 0;
}

static void gs_os_write_stdout(sl_u8 s) {
    if (s.len > 0) fwrite(s.data, 1, (size_t)s.len, stdout);
}

static void gs_os_write_stderr(sl_u8 s) {
    if (s.len > 0) fwrite(s.data, 1, (size_t)s.len, stderr);
}

static void gs_os_flush_stdout(void) { fflush(stdout); }

/* One line of stdin, without its newline; false at end of input. */
static uint8_t gs_os_read_line(gs_rref out) {
    int c = fgetc(stdin);
    if (c == EOF) return 0;
    while (c != EOF && c != '\n') {
        uint8_t b = (uint8_t)c;
        gs_bld_append(out, &b, 1);
        c = fgetc(stdin);
    }
    if (out.hdr->len > 0 && out.hdr->base[out.hdr->len - 1] == '\r') {
        out.hdr->len--;
        out.stk->top--;
    }
    return 1;
}

/* All of stdin. */
static void gs_os_read_stdin(gs_rref out) {
    uint8_t buf[65536];
    for (;;) {
        size_t n = fread(buf, 1, sizeof buf, stdin);
        if (n == 0) break;
        gs_bld_append(out, buf, (int64_t)n);
    }
}

static int64_t gs_os_arg_count(void) { return gs_argc; }

static void gs_os_arg(int64_t i, gs_rref out) {
    if (i < 0 || i >= gs_argc) return;
    const char *a = gs_argv[i];
#ifdef _WIN32
    /* main's argv is in the ANSI code page. The program gets it in UTF-8,
       the encoding of its paths, by way of UTF-16, which holds every
       character of the code page. */
    int n = MultiByteToWideChar(CP_ACP, 0, a, -1, NULL, 0);
    wchar_t *w = n > 0 ? (wchar_t *)malloc((size_t)n * sizeof *w) : NULL;
    int ok = w && MultiByteToWideChar(CP_ACP, 0, a, -1, w, n) == n &&
             gs_os_append_wide(out, w, n - 1);
    free(w);
    if (ok) return;
#endif
    gs_bld_append(out, a, (int64_t)strlen(a));
}

static uint8_t gs_os_getenv(sl_u8 name, gs_rref out) {
    gs_os_char nm[GS_OS_PATH_MAX];
    if (gs_os_native(name, nm) < 0) return 0;
#ifdef _WIN32
    /* The environment holds UTF-16, which getenv would hand out in the ANSI
       code page. A value can change size between the calls. */
    wchar_t small[512], *v = small;
    DWORD cap = 512, len;
    for (;;) {
        SetLastError(0);
        len = GetEnvironmentVariableW(nm, v, cap);
        if (len < cap) break;
        if (v != small) free(v);
        cap = len;
        v = (wchar_t *)malloc(cap * sizeof *v);
        if (!v) return 0;
    }
    /* Zero is also the length of an empty value. */
    int ok = (len > 0 || GetLastError() != ERROR_ENVVAR_NOT_FOUND) &&
             gs_os_append_wide(out, v, (int)len);
    if (v != small) free(v);
    return ok ? 1 : 0;
#else
    const char *v = getenv(nm);
    if (!v) return 0;
    gs_bld_append(out, v, (int64_t)strlen(v));
    return 1;
#endif
}

/* Wall-clock time in nanoseconds since the Unix epoch. */
static int64_t gs_os_time_ns(void) {
    /* Neither branch uses C11's timespec_get: the Microsoft C runtime tcc
       links against does not have it, and glibc hides it from a compiler
       announcing C99, which tcc also is. */
#ifdef _WIN32
    /* Windows counts 100 ns ticks from 1601; the offset to the Unix epoch is
       a constant. */
    FILETIME ft;
    GetSystemTimeAsFileTime(&ft);
)GSRT"
R"GSRT(    uint64_t t = ((uint64_t)ft.dwHighDateTime << 32) | ft.dwLowDateTime;
    return (int64_t)(t - 116444736000000000ull) * 100;
#else
    struct timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts);
    return (int64_t)ts.tv_sec * 1000000000 + ts.tv_nsec;
#endif
}

/* A monotonic clock in nanoseconds, for measuring intervals. */
static int64_t gs_os_clock_ns(void) {
#ifdef _WIN32
    LARGE_INTEGER f, c;
    QueryPerformanceFrequency(&f);
    QueryPerformanceCounter(&c);
    return (int64_t)((double)c.QuadPart * (1000000000.0 / (double)f.QuadPart));
#else
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (int64_t)ts.tv_sec * 1000000000 + ts.tv_nsec;
#endif
}

static void gs_os_sleep_ms(int64_t ms) {
    if (ms <= 0) return;
#ifdef _WIN32
    Sleep((DWORD)ms);
#else
    struct timespec ts;
    ts.tv_sec = (time_t)(ms / 1000);
    ts.tv_nsec = (long)((ms % 1000) * 1000000);
    nanosleep(&ts, NULL);
#endif
}

/* Entropy for seeding a PRNG (not cryptographic): /dev/urandom where there
   is one; on Windows a splitmix64 mix of the clocks, the process id and an
   address, which needs no library beyond the runtime's. */
static uint64_t gs_os_mix64(uint64_t x) {
    x += 0x9e3779b97f4a7c15u;
    x = (x ^ (x >> 30)) * 0xbf58476d1ce4e5b9u;
    x = (x ^ (x >> 27)) * 0x94d049bb133111ebu;
    return x ^ (x >> 31);
}

static uint64_t gs_os_random_u64(void) {
#ifndef _WIN32
    FILE *f = fopen("/dev/urandom", "rb");
    if (f) {
        uint64_t v = 0;
        size_t n = fread(&v, 1, sizeof v, f);
        fclose(f);
        if (n == sizeof v) return v;
    }
#endif
    static uint64_t counter;
    uint64_t seed = (uint64_t)gs_os_time_ns();
    seed = gs_os_mix64(seed ^ (uint64_t)gs_os_clock_ns());
#ifdef _WIN32
    seed = gs_os_mix64(seed ^ (uint64_t)GetCurrentProcessId());
#endif
    seed = gs_os_mix64(seed ^ (uint64_t)(uintptr_t)&counter);
    return gs_os_mix64(seed ^ ++counter);
}
)GSRT"
    ) },
};

}  // namespace goose
